// Package influxdb3core provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package influxdb3core

import (
	"time"
)

const (
	BasicAuthenticationScopes       = "BasicAuthentication.Scopes"
	BearerAuthenticationScopes      = "BearerAuthentication.Scopes"
	QuerystringAuthenticationScopes = "QuerystringAuthentication.Scopes"
	TokenAuthenticationScopes       = "TokenAuthentication.Scopes"
)

// Defines values for ContentEncoding.
const (
	ContentEncodingGzip     ContentEncoding = "gzip"
	ContentEncodingIdentity ContentEncoding = "identity"
)

// Valid indicates whether the value is a known member of the ContentEncoding enum.
func (e ContentEncoding) Valid() bool {
	switch e {
	case ContentEncodingGzip:
		return true
	case ContentEncodingIdentity:
		return true
	default:
		return false
	}
}

// Defines values for CreateTableRequestFieldsType.
const (
	Bool    CreateTableRequestFieldsType = "bool"
	Float64 CreateTableRequestFieldsType = "float64"
	Int64   CreateTableRequestFieldsType = "int64"
	Uint64  CreateTableRequestFieldsType = "uint64"
	Utf8    CreateTableRequestFieldsType = "utf8"
)

// Valid indicates whether the value is a known member of the CreateTableRequestFieldsType enum.
func (e CreateTableRequestFieldsType) Valid() bool {
	switch e {
	case Bool:
		return true
	case Float64:
		return true
	case Int64:
		return true
	case Uint64:
		return true
	case Utf8:
		return true
	default:
		return false
	}
}

// Defines values for EpochCompatibility.
const (
	EpochCompatibilityH  EpochCompatibility = "h"
	EpochCompatibilityM  EpochCompatibility = "m"
	EpochCompatibilityMs EpochCompatibility = "ms"
	EpochCompatibilityNs EpochCompatibility = "ns"
	EpochCompatibilityS  EpochCompatibility = "s"
	EpochCompatibilityU  EpochCompatibility = "u"
	EpochCompatibilityΜ  EpochCompatibility = "µ"
)

// Valid indicates whether the value is a known member of the EpochCompatibility enum.
func (e EpochCompatibility) Valid() bool {
	switch e {
	case EpochCompatibilityH:
		return true
	case EpochCompatibilityM:
		return true
	case EpochCompatibilityMs:
		return true
	case EpochCompatibilityNs:
		return true
	case EpochCompatibilityS:
		return true
	case EpochCompatibilityU:
		return true
	case EpochCompatibilityΜ:
		return true
	default:
		return false
	}
}

// Defines values for Format.
const (
	FormatCsv       Format = "csv"
	FormatJson      Format = "json"
	FormatJsonLines Format = "json_lines"
	FormatJsonl     Format = "jsonl"
	FormatParquet   Format = "parquet"
	FormatPretty    Format = "pretty"
)

// Valid indicates whether the value is a known member of the Format enum.
func (e Format) Valid() bool {
	switch e {
	case FormatCsv:
		return true
	case FormatJson:
		return true
	case FormatJsonLines:
		return true
	case FormatJsonl:
		return true
	case FormatParquet:
		return true
	case FormatPretty:
		return true
	default:
		return false
	}
}

// Defines values for LineProtocol.
const (
	Textplain            LineProtocol = "text/plain"
	TextplainCharsetUtf8 LineProtocol = "text/plain; charset=utf-8"
)

// Valid indicates whether the value is a known member of the LineProtocol enum.
func (e LineProtocol) Valid() bool {
	switch e {
	case Textplain:
		return true
	case TextplainCharsetUtf8:
		return true
	default:
		return false
	}
}

// Defines values for PrecisionWrite.
const (
	Auto        PrecisionWrite = "auto"
	Microsecond PrecisionWrite = "microsecond"
	Millisecond PrecisionWrite = "millisecond"
	Nanosecond  PrecisionWrite = "nanosecond"
	Second      PrecisionWrite = "second"
)

// Valid indicates whether the value is a known member of the PrecisionWrite enum.
func (e PrecisionWrite) Valid() bool {
	switch e {
	case Auto:
		return true
	case Microsecond:
		return true
	case Millisecond:
		return true
	case Nanosecond:
		return true
	case Second:
		return true
	default:
		return false
	}
}

// Defines values for PrecisionWriteCompatibility.
const (
	PrecisionWriteCompatibilityMs PrecisionWriteCompatibility = "ms"
	PrecisionWriteCompatibilityN  PrecisionWriteCompatibility = "n"
	PrecisionWriteCompatibilityNs PrecisionWriteCompatibility = "ns"
	PrecisionWriteCompatibilityS  PrecisionWriteCompatibility = "s"
	PrecisionWriteCompatibilityU  PrecisionWriteCompatibility = "u"
	PrecisionWriteCompatibilityUs PrecisionWriteCompatibility = "us"
)

// Valid indicates whether the value is a known member of the PrecisionWriteCompatibility enum.
func (e PrecisionWriteCompatibility) Valid() bool {
	switch e {
	case PrecisionWriteCompatibilityMs:
		return true
	case PrecisionWriteCompatibilityN:
		return true
	case PrecisionWriteCompatibilityNs:
		return true
	case PrecisionWriteCompatibilityS:
		return true
	case PrecisionWriteCompatibilityU:
		return true
	case PrecisionWriteCompatibilityUs:
		return true
	default:
		return false
	}
}

// Defines values for QueryRequestObjectFormat.
const (
	QueryRequestObjectFormatCsv       QueryRequestObjectFormat = "csv"
	QueryRequestObjectFormatJson      QueryRequestObjectFormat = "json"
	QueryRequestObjectFormatJsonLines QueryRequestObjectFormat = "json_lines"
	QueryRequestObjectFormatJsonl     QueryRequestObjectFormat = "jsonl"
	QueryRequestObjectFormatParquet   QueryRequestObjectFormat = "parquet"
	QueryRequestObjectFormatPretty    QueryRequestObjectFormat = "pretty"
)

// Valid indicates whether the value is a known member of the QueryRequestObjectFormat enum.
func (e QueryRequestObjectFormat) Valid() bool {
	switch e {
	case QueryRequestObjectFormatCsv:
		return true
	case QueryRequestObjectFormatJson:
		return true
	case QueryRequestObjectFormatJsonLines:
		return true
	case QueryRequestObjectFormatJsonl:
		return true
	case QueryRequestObjectFormatParquet:
		return true
	case QueryRequestObjectFormatPretty:
		return true
	default:
		return false
	}
}

// Defines values for TriggerSettingsErrorBehavior.
const (
	Disable TriggerSettingsErrorBehavior = "Disable"
	Log     TriggerSettingsErrorBehavior = "Log"
	Retry   TriggerSettingsErrorBehavior = "Retry"
)

// Valid indicates whether the value is a known member of the TriggerSettingsErrorBehavior enum.
func (e TriggerSettingsErrorBehavior) Valid() bool {
	switch e {
	case Disable:
		return true
	case Log:
		return true
	case Retry:
		return true
	default:
		return false
	}
}

// Defines values for AcceptQueryHeader.
const (
	AcceptQueryHeaderApplicationjson             AcceptQueryHeader = "application/json"
	AcceptQueryHeaderApplicationjsonl            AcceptQueryHeader = "application/jsonl"
	AcceptQueryHeaderApplicationvndApacheParquet AcceptQueryHeader = "application/vnd.apache.parquet"
	AcceptQueryHeaderTextcsv                     AcceptQueryHeader = "text/csv"
)

// Valid indicates whether the value is a known member of the AcceptQueryHeader enum.
func (e AcceptQueryHeader) Valid() bool {
	switch e {
	case AcceptQueryHeaderApplicationjson:
		return true
	case AcceptQueryHeaderApplicationjsonl:
		return true
	case AcceptQueryHeaderApplicationvndApacheParquet:
		return true
	case AcceptQueryHeaderTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for ContentType.
const (
	ContentTypeApplicationjson ContentType = "application/json"
)

// Valid indicates whether the value is a known member of the ContentType enum.
func (e ContentType) Valid() bool {
	switch e {
	case ContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for PostV2WriteParamsContentEncoding.
const (
	PostV2WriteParamsContentEncodingGzip     PostV2WriteParamsContentEncoding = "gzip"
	PostV2WriteParamsContentEncodingIdentity PostV2WriteParamsContentEncoding = "identity"
)

// Valid indicates whether the value is a known member of the PostV2WriteParamsContentEncoding enum.
func (e PostV2WriteParamsContentEncoding) Valid() bool {
	switch e {
	case PostV2WriteParamsContentEncodingGzip:
		return true
	case PostV2WriteParamsContentEncodingIdentity:
		return true
	default:
		return false
	}
}

// Defines values for PostV2WriteParamsAccept.
const (
	PostV2WriteParamsAcceptApplicationjson PostV2WriteParamsAccept = "application/json"
)

// Valid indicates whether the value is a known member of the PostV2WriteParamsAccept enum.
func (e PostV2WriteParamsAccept) Valid() bool {
	switch e {
	case PostV2WriteParamsAcceptApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for PostInstallPluginPackagesParamsContentType.
const (
	PostInstallPluginPackagesParamsContentTypeApplicationjson PostInstallPluginPackagesParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the PostInstallPluginPackagesParamsContentType enum.
func (e PostInstallPluginPackagesParamsContentType) Valid() bool {
	switch e {
	case PostInstallPluginPackagesParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for PostInstallPluginRequirementsParamsContentType.
const (
	PostInstallPluginRequirementsParamsContentTypeApplicationjson PostInstallPluginRequirementsParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the PostInstallPluginRequirementsParamsContentType enum.
func (e PostInstallPluginRequirementsParamsContentType) Valid() bool {
	switch e {
	case PostInstallPluginRequirementsParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for PostProcessingEnginePluginRequestParamsContentType.
const (
	PostProcessingEnginePluginRequestParamsContentTypeApplicationjson PostProcessingEnginePluginRequestParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the PostProcessingEnginePluginRequestParamsContentType enum.
func (e PostProcessingEnginePluginRequestParamsContentType) Valid() bool {
	switch e {
	case PostProcessingEnginePluginRequestParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for GetExecuteInfluxQLQueryParamsAccept.
const (
	GetExecuteInfluxQLQueryParamsAcceptApplicationjson             GetExecuteInfluxQLQueryParamsAccept = "application/json"
	GetExecuteInfluxQLQueryParamsAcceptApplicationjsonl            GetExecuteInfluxQLQueryParamsAccept = "application/jsonl"
	GetExecuteInfluxQLQueryParamsAcceptApplicationvndApacheParquet GetExecuteInfluxQLQueryParamsAccept = "application/vnd.apache.parquet"
	GetExecuteInfluxQLQueryParamsAcceptTextcsv                     GetExecuteInfluxQLQueryParamsAccept = "text/csv"
)

// Valid indicates whether the value is a known member of the GetExecuteInfluxQLQueryParamsAccept enum.
func (e GetExecuteInfluxQLQueryParamsAccept) Valid() bool {
	switch e {
	case GetExecuteInfluxQLQueryParamsAcceptApplicationjson:
		return true
	case GetExecuteInfluxQLQueryParamsAcceptApplicationjsonl:
		return true
	case GetExecuteInfluxQLQueryParamsAcceptApplicationvndApacheParquet:
		return true
	case GetExecuteInfluxQLQueryParamsAcceptTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteQueryInfluxQLParamsAccept.
const (
	PostExecuteQueryInfluxQLParamsAcceptApplicationjson             PostExecuteQueryInfluxQLParamsAccept = "application/json"
	PostExecuteQueryInfluxQLParamsAcceptApplicationjsonl            PostExecuteQueryInfluxQLParamsAccept = "application/jsonl"
	PostExecuteQueryInfluxQLParamsAcceptApplicationvndApacheParquet PostExecuteQueryInfluxQLParamsAccept = "application/vnd.apache.parquet"
	PostExecuteQueryInfluxQLParamsAcceptTextcsv                     PostExecuteQueryInfluxQLParamsAccept = "text/csv"
)

// Valid indicates whether the value is a known member of the PostExecuteQueryInfluxQLParamsAccept enum.
func (e PostExecuteQueryInfluxQLParamsAccept) Valid() bool {
	switch e {
	case PostExecuteQueryInfluxQLParamsAcceptApplicationjson:
		return true
	case PostExecuteQueryInfluxQLParamsAcceptApplicationjsonl:
		return true
	case PostExecuteQueryInfluxQLParamsAcceptApplicationvndApacheParquet:
		return true
	case PostExecuteQueryInfluxQLParamsAcceptTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteQueryInfluxQLParamsContentType.
const (
	PostExecuteQueryInfluxQLParamsContentTypeApplicationjson PostExecuteQueryInfluxQLParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the PostExecuteQueryInfluxQLParamsContentType enum.
func (e PostExecuteQueryInfluxQLParamsContentType) Valid() bool {
	switch e {
	case PostExecuteQueryInfluxQLParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for GetExecuteQuerySQLParamsAccept.
const (
	GetExecuteQuerySQLParamsAcceptApplicationjson             GetExecuteQuerySQLParamsAccept = "application/json"
	GetExecuteQuerySQLParamsAcceptApplicationjsonl            GetExecuteQuerySQLParamsAccept = "application/jsonl"
	GetExecuteQuerySQLParamsAcceptApplicationvndApacheParquet GetExecuteQuerySQLParamsAccept = "application/vnd.apache.parquet"
	GetExecuteQuerySQLParamsAcceptTextcsv                     GetExecuteQuerySQLParamsAccept = "text/csv"
)

// Valid indicates whether the value is a known member of the GetExecuteQuerySQLParamsAccept enum.
func (e GetExecuteQuerySQLParamsAccept) Valid() bool {
	switch e {
	case GetExecuteQuerySQLParamsAcceptApplicationjson:
		return true
	case GetExecuteQuerySQLParamsAcceptApplicationjsonl:
		return true
	case GetExecuteQuerySQLParamsAcceptApplicationvndApacheParquet:
		return true
	case GetExecuteQuerySQLParamsAcceptTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for GetExecuteQuerySQLParamsContentType.
const (
	GetExecuteQuerySQLParamsContentTypeApplicationjson GetExecuteQuerySQLParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the GetExecuteQuerySQLParamsContentType enum.
func (e GetExecuteQuerySQLParamsContentType) Valid() bool {
	switch e {
	case GetExecuteQuerySQLParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteQuerySQLParamsAccept.
const (
	PostExecuteQuerySQLParamsAcceptApplicationjson             PostExecuteQuerySQLParamsAccept = "application/json"
	PostExecuteQuerySQLParamsAcceptApplicationjsonl            PostExecuteQuerySQLParamsAccept = "application/jsonl"
	PostExecuteQuerySQLParamsAcceptApplicationvndApacheParquet PostExecuteQuerySQLParamsAccept = "application/vnd.apache.parquet"
	PostExecuteQuerySQLParamsAcceptTextcsv                     PostExecuteQuerySQLParamsAccept = "text/csv"
)

// Valid indicates whether the value is a known member of the PostExecuteQuerySQLParamsAccept enum.
func (e PostExecuteQuerySQLParamsAccept) Valid() bool {
	switch e {
	case PostExecuteQuerySQLParamsAcceptApplicationjson:
		return true
	case PostExecuteQuerySQLParamsAcceptApplicationjsonl:
		return true
	case PostExecuteQuerySQLParamsAcceptApplicationvndApacheParquet:
		return true
	case PostExecuteQuerySQLParamsAcceptTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteQuerySQLParamsContentType.
const (
	PostExecuteQuerySQLParamsContentTypeApplicationjson PostExecuteQuerySQLParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the PostExecuteQuerySQLParamsContentType enum.
func (e PostExecuteQuerySQLParamsContentType) Valid() bool {
	switch e {
	case PostExecuteQuerySQLParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for PostWriteLPParamsAccept.
const (
	PostWriteLPParamsAcceptApplicationjson PostWriteLPParamsAccept = "application/json"
)

// Valid indicates whether the value is a known member of the PostWriteLPParamsAccept enum.
func (e PostWriteLPParamsAccept) Valid() bool {
	switch e {
	case PostWriteLPParamsAcceptApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for GetV1ExecuteQueryParamsAccept.
const (
	GetV1ExecuteQueryParamsAcceptApplicationcsv  GetV1ExecuteQueryParamsAccept = "application/csv"
	GetV1ExecuteQueryParamsAcceptApplicationjson GetV1ExecuteQueryParamsAccept = "application/json"
	GetV1ExecuteQueryParamsAcceptTextcsv         GetV1ExecuteQueryParamsAccept = "text/csv"
)

// Valid indicates whether the value is a known member of the GetV1ExecuteQueryParamsAccept enum.
func (e GetV1ExecuteQueryParamsAccept) Valid() bool {
	switch e {
	case GetV1ExecuteQueryParamsAcceptApplicationcsv:
		return true
	case GetV1ExecuteQueryParamsAcceptApplicationjson:
		return true
	case GetV1ExecuteQueryParamsAcceptTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteV1QueryParamsAccept.
const (
	PostExecuteV1QueryParamsAcceptApplicationcsv  PostExecuteV1QueryParamsAccept = "application/csv"
	PostExecuteV1QueryParamsAcceptApplicationjson PostExecuteV1QueryParamsAccept = "application/json"
	PostExecuteV1QueryParamsAcceptTextcsv         PostExecuteV1QueryParamsAccept = "text/csv"
)

// Valid indicates whether the value is a known member of the PostExecuteV1QueryParamsAccept enum.
func (e PostExecuteV1QueryParamsAccept) Valid() bool {
	switch e {
	case PostExecuteV1QueryParamsAcceptApplicationcsv:
		return true
	case PostExecuteV1QueryParamsAcceptApplicationjson:
		return true
	case PostExecuteV1QueryParamsAcceptTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteV1QueryJSONBodyEpoch.
const (
	PostExecuteV1QueryJSONBodyEpochH  PostExecuteV1QueryJSONBodyEpoch = "h"
	PostExecuteV1QueryJSONBodyEpochM  PostExecuteV1QueryJSONBodyEpoch = "m"
	PostExecuteV1QueryJSONBodyEpochMs PostExecuteV1QueryJSONBodyEpoch = "ms"
	PostExecuteV1QueryJSONBodyEpochNs PostExecuteV1QueryJSONBodyEpoch = "ns"
	PostExecuteV1QueryJSONBodyEpochS  PostExecuteV1QueryJSONBodyEpoch = "s"
	PostExecuteV1QueryJSONBodyEpochU  PostExecuteV1QueryJSONBodyEpoch = "u"
	PostExecuteV1QueryJSONBodyEpochΜ  PostExecuteV1QueryJSONBodyEpoch = "µ"
)

// Valid indicates whether the value is a known member of the PostExecuteV1QueryJSONBodyEpoch enum.
func (e PostExecuteV1QueryJSONBodyEpoch) Valid() bool {
	switch e {
	case PostExecuteV1QueryJSONBodyEpochH:
		return true
	case PostExecuteV1QueryJSONBodyEpochM:
		return true
	case PostExecuteV1QueryJSONBodyEpochMs:
		return true
	case PostExecuteV1QueryJSONBodyEpochNs:
		return true
	case PostExecuteV1QueryJSONBodyEpochS:
		return true
	case PostExecuteV1QueryJSONBodyEpochU:
		return true
	case PostExecuteV1QueryJSONBodyEpochΜ:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteV1QueryFormdataBodyEpoch.
const (
	PostExecuteV1QueryFormdataBodyEpochH  PostExecuteV1QueryFormdataBodyEpoch = "h"
	PostExecuteV1QueryFormdataBodyEpochM  PostExecuteV1QueryFormdataBodyEpoch = "m"
	PostExecuteV1QueryFormdataBodyEpochMs PostExecuteV1QueryFormdataBodyEpoch = "ms"
	PostExecuteV1QueryFormdataBodyEpochNs PostExecuteV1QueryFormdataBodyEpoch = "ns"
	PostExecuteV1QueryFormdataBodyEpochS  PostExecuteV1QueryFormdataBodyEpoch = "s"
	PostExecuteV1QueryFormdataBodyEpochU  PostExecuteV1QueryFormdataBodyEpoch = "u"
	PostExecuteV1QueryFormdataBodyEpochΜ  PostExecuteV1QueryFormdataBodyEpoch = "µ"
)

// Valid indicates whether the value is a known member of the PostExecuteV1QueryFormdataBodyEpoch enum.
func (e PostExecuteV1QueryFormdataBodyEpoch) Valid() bool {
	switch e {
	case PostExecuteV1QueryFormdataBodyEpochH:
		return true
	case PostExecuteV1QueryFormdataBodyEpochM:
		return true
	case PostExecuteV1QueryFormdataBodyEpochMs:
		return true
	case PostExecuteV1QueryFormdataBodyEpochNs:
		return true
	case PostExecuteV1QueryFormdataBodyEpochS:
		return true
	case PostExecuteV1QueryFormdataBodyEpochU:
		return true
	case PostExecuteV1QueryFormdataBodyEpochΜ:
		return true
	default:
		return false
	}
}

// Defines values for PostV1WriteParamsAccept.
const (
	Applicationjson PostV1WriteParamsAccept = "application/json"
)

// Valid indicates whether the value is a known member of the PostV1WriteParamsAccept enum.
func (e PostV1WriteParamsAccept) Valid() bool {
	switch e {
	case Applicationjson:
		return true
	default:
		return false
	}
}

// AcceptPartial Accept partial writes.
type AcceptPartial = bool

// AdminTokenObject defines model for AdminTokenObject.
type AdminTokenObject struct {
	CreatedAt *time.Time  `json:"created_at,omitempty"`
	Expiry    interface{} `json:"expiry,omitempty"`
	Hash      *string     `json:"hash,omitempty"`
	Id        *int        `json:"id,omitempty"`
	Name      *string     `json:"name,omitempty"`
	Token     *string     `json:"token,omitempty"`
}

// ContentEncoding Content coding.
// Use `gzip` for compressed data or `identity` for unmodified, uncompressed data.
//
// #### Multi-member gzip support
//
// InfluxDB 3 supports multi-member gzip payloads (concatenated gzip files per [RFC 1952](https://www.rfc-editor.org/rfc/rfc1952)).
// This allows you to:
// - Concatenate multiple gzip files and send them in a single request
// - Maintain compatibility with InfluxDB v1 and v2 write endpoints
// - Simplify batch operations using standard compression tools
type ContentEncoding string

// ContentLength The length in decimal number of octets.
type ContentLength = int

// CreateDatabaseRequest defines model for CreateDatabaseRequest.
type CreateDatabaseRequest struct {
	// Db The database name. Database names cannot contain underscores (_).
	// Names must start and end with alphanumeric characters and can contain hyphens (-) in the middle.
	Db string `json:"db"`

	// RetentionPeriod The retention period for the database. Specifies how long data should be retained.
	// Use duration format (for example, "1d", "1h", "30m", "7d").
	RetentionPeriod *string `json:"retention_period,omitempty"`
}

// CreateTableRequest defines model for CreateTableRequest.
type CreateTableRequest struct {
	Db     string `json:"db"`
	Fields []struct {
		Name string                       `json:"name"`
		Type CreateTableRequestFieldsType `json:"type"`
	} `json:"fields"`

	// RetentionPeriod The retention period for the table. Specifies how long data in this table should be retained.
	// Use duration format (for example, "1d", "1h", "30m", "7d").
	RetentionPeriod *string  `json:"retention_period,omitempty"`
	Table           string   `json:"table"`
	Tags            []string `json:"tags"`
}

// CreateTableRequestFieldsType defines model for CreateTableRequest.Fields.Type.
type CreateTableRequestFieldsType string

// DistinctCacheCreateRequest defines model for DistinctCacheCreateRequest.
type DistinctCacheCreateRequest struct {
	Columns []string `json:"columns"`
	Db      string   `json:"db"`

	// MaxAge Optional maximum age in seconds.
	MaxAge *int `json:"max_age,omitempty"`

	// MaxCardinality Optional maximum cardinality.
	MaxCardinality *int `json:"max_cardinality,omitempty"`

	// Name Optional cache name.
	Name  *string `json:"name,omitempty"`
	Table string  `json:"table"`
}

// EpochCompatibility A unix timestamp precision.
// - `h` for hours
// - `m` for minutes
// - `s` for seconds
// - `ms` for milliseconds
// - `u` or `µ` for microseconds
// - `ns` for nanoseconds
type EpochCompatibility string

// ErrorMessage defines model for ErrorMessage.
type ErrorMessage struct {
	Data  *map[string]interface{} `json:"data,omitempty"`
	Error *string                 `json:"error,omitempty"`
}

// Format The format of data in the response body.
// `json_lines` is the canonical name; `jsonl` is accepted as an alias.
type Format string

// LastCacheCreateRequest defines model for LastCacheCreateRequest.
type LastCacheCreateRequest struct {
	// Count Optional count.
	Count *int   `json:"count,omitempty"`
	Db    string `json:"db"`

	// KeyColumns Optional list of key columns.
	KeyColumns *[]string `json:"key_columns,omitempty"`

	// Name Optional cache name.
	Name  *string `json:"name,omitempty"`
	Table string  `json:"table"`

	// Ttl Optional time-to-live in seconds.
	Ttl *int `json:"ttl,omitempty"`

	// ValueColumns Optional list of value columns.
	ValueColumns *[]string `json:"value_columns,omitempty"`
}

// LineProtocol `text/plain` is the content type for line protocol. `UTF-8` is the default character set.
type LineProtocol string

// NoSync Acknowledges a successful write without waiting for WAL persistence.
//
// #### Related
//
// - [Use the HTTP API and client libraries to write data](/influxdb3/core/write-data/api-client-libraries/)
// - [Data durability](/influxdb3/core/reference/internals/durability/)
type NoSync = bool

// PluginDirectoryRequest Request body for updating plugin directory with multiple files.
type PluginDirectoryRequest struct {
	// Files List of plugin files to include in the directory.
	Files []PluginFileEntry `json:"files"`

	// PluginName The name of the plugin directory to update.
	PluginName string `json:"plugin_name"`
}

// PluginFileEntry Represents a single file in a plugin directory.
type PluginFileEntry struct {
	// Content The content of the file.
	Content string `json:"content"`

	// RelativePath The relative path of the file within the plugin directory.
	RelativePath string `json:"relative_path"`
}

// PluginFileRequest Request body for updating a plugin file.
type PluginFileRequest struct {
	// Content The content of the plugin file.
	Content string `json:"content"`

	// PluginName The name of the plugin file to update.
	PluginName string `json:"plugin_name"`
}

// PrecisionWrite The precision for unix timestamps in the line protocol batch.
//
// Supported values:
// - `auto` (default): Automatically detects precision based on timestamp magnitude
// - `nanosecond`: Nanoseconds
// - `microsecond`: Microseconds
// - `millisecond`: Milliseconds
// - `second`: Seconds
type PrecisionWrite string

// PrecisionWriteCompatibility The precision for unix timestamps in the line protocol batch.
// Use `ms` for milliseconds, `s` for seconds, `us` or `u` for microseconds, or `ns` or `n` for nanoseconds.
// Optional — defaults to nanosecond precision if omitted.
type PrecisionWriteCompatibility string

// ProcessingEngineTriggerRequest defines model for ProcessingEngineTriggerRequest.
type ProcessingEngineTriggerRequest struct {
	Db string `json:"db"`

	// Disabled Whether the trigger is disabled.
	Disabled bool `json:"disabled"`

	// PluginFilename The path and filename of the plugin to execute--for example,
	// `schedule.py` or `endpoints/report.py`.
	// The path can be absolute or relative to the `--plugins-dir` directory configured when starting InfluxDB 3.
	//
	// The plugin file must implement the trigger interface associated with the trigger's specification.
	PluginFilename string `json:"plugin_filename"`

	// TriggerArguments Optional arguments passed to the plugin.
	TriggerArguments *map[string]interface{} `json:"trigger_arguments,omitempty"`
	TriggerName      string                  `json:"trigger_name"`

	// TriggerSettings Configuration for trigger error handling and execution behavior.
	TriggerSettings TriggerSettings `json:"trigger_settings"`

	// TriggerSpecification Specifies when and how the processing engine trigger should be invoked.
	//
	// ## Supported trigger specifications:
	//
	// ### Cron-based scheduling
	// Format: `cron:CRON_EXPRESSION`
	//
	// Uses extended (6-field) cron format (second minute hour day_of_month month day_of_week):
	// ```
	// ┌───────────── second (0-59)
	// │ ┌───────────── minute (0-59)
	// │ │ ┌───────────── hour (0-23)
	// │ │ │ ┌───────────── day of month (1-31)
	// │ │ │ │ ┌───────────── month (1-12)
	// │ │ │ │ │ ┌───────────── day of week (0-6, Sunday=0)
	// │ │ │ │ │ │
	// * * * * * *
	// ```
	// Examples:
	// - `cron:0 0 6 * * 1-5` - Every weekday at 6:00 AM
	// - `cron:0 30 14 * * 5` - Every Friday at 2:30 PM
	// - `cron:0 0 0 1 * *` - First day of every month at midnight
	//
	// ### Interval-based scheduling
	// Format: `every:DURATION`
	//
	// Supported durations: `s` (seconds), `m` (minutes), `h` (hours), `d` (days), `w` (weeks), `M` (months), `y` (years):
	// - `every:30s` - Every 30 seconds
	// - `every:5m` - Every 5 minutes
	// - `every:1h` - Every hour
	// - `every:1d` - Every day
	// - `every:1w` - Every week
	// - `every:1M` - Every month
	// - `every:1y` - Every year
	//
	// **Maximum interval**: 1 year
	//
	// ### Table-based triggers
	// - `all_tables` - Triggers on write events to any table in the database
	// - `table:TABLE_NAME` - Triggers on write events to a specific table
	//
	// ### On-demand triggers
	// Format: `request:REQUEST_PATH`
	//
	// Creates an HTTP endpoint `/api/v3/engine/REQUEST_PATH` for manual invocation:
	// - `request:hello-world` - Creates endpoint `/api/v3/engine/hello-world`
	// - `request:data-export` - Creates endpoint `/api/v3/engine/data-export`
	TriggerSpecification interface{} `json:"trigger_specification"`
}

// QueryRequestObject defines model for QueryRequestObject.
type QueryRequestObject struct {
	// Db The name of the database to query.
	// Required if the query (`q`) doesn't specify the database.
	Db string `json:"db"`

	// Format The format of the query results.
	Format *QueryRequestObjectFormat `json:"format,omitempty"`

	// Params Additional parameters for the query.
	// Use this field to pass query parameters.
	Params *map[string]interface{} `json:"params,omitempty"`

	// Q The query to execute.
	Q string `json:"q"`
}

// QueryRequestObjectFormat The format of the query results.
type QueryRequestObjectFormat string

// QueryResponse defines model for QueryResponse.
type QueryResponse struct {
	Results *[]map[string]interface{} `json:"results,omitempty"`
}

// SchedulePluginTestRequest Request body for testing a scheduling plugin.
type SchedulePluginTestRequest struct {
	// CacheName Optional name of the cache to use in the test.
	CacheName *string `json:"cache_name,omitempty"`

	// Database The database name to use for the test.
	Database string `json:"database"`

	// Filename The path and filename of the plugin to test.
	Filename string `json:"filename"`

	// InputArguments Optional key-value pairs of arguments to pass to the plugin.
	InputArguments *map[string]string `json:"input_arguments,omitempty"`

	// Schedule Optional schedule specification in cron or interval format.
	Schedule *string `json:"schedule,omitempty"`
}

// ShowDatabasesResponse defines model for ShowDatabasesResponse.
type ShowDatabasesResponse struct {
	Databases *[]string `json:"databases,omitempty"`
}

// TriggerSettings Configuration settings for processing engine trigger error handling and execution behavior.
type TriggerSettings struct {
	// ErrorBehavior Specifies how to handle errors that occur during trigger execution:
	// - `Log`: Log the error and continue (default)
	// - `Retry`: Retry the trigger execution
	// - `Disable`: Disable the trigger after an error
	ErrorBehavior TriggerSettingsErrorBehavior `json:"error_behavior"`

	// RunAsync Whether to run the trigger asynchronously.
	// When `true`, the trigger executes in the background without blocking.
	// When `false`, the trigger executes synchronously.
	RunAsync bool `json:"run_async"`
}

// TriggerSettingsErrorBehavior Specifies how to handle errors that occur during trigger execution:
// - `Log`: Log the error and continue (default)
// - `Retry`: Retry the trigger execution
// - `Disable`: Disable the trigger after an error
type TriggerSettingsErrorBehavior string

// UpdateDatabaseRequest Request schema for updating database configuration.
type UpdateDatabaseRequest struct {
	// RetentionPeriod The retention period for the database. Specifies how long data should be retained.
	// Use duration format (for example, "1d", "1h", "30m", "7d").
	RetentionPeriod *string `json:"retention_period,omitempty"`
}

// WALPluginTestRequest Request body for testing a write-ahead logging (WAL) plugin.
type WALPluginTestRequest struct {
	// CacheName Optional name of the cache to use in the test.
	CacheName *string `json:"cache_name,omitempty"`

	// Database The database name to use for the test.
	Database string `json:"database"`

	// Filename The path and filename of the plugin to test.
	Filename string `json:"filename"`

	// InputArguments Optional key-value pairs of arguments to pass to the plugin.
	InputArguments *map[string]string `json:"input_arguments,omitempty"`

	// InputLp Line protocol data to use as input for the test.
	InputLp string `json:"input_lp"`
}

// AcceptQueryHeader defines model for AcceptQueryHeader.
type AcceptQueryHeader string

// ContentType defines model for ContentType.
type ContentType string

// CompatibilityPrecisionParam The precision for unix timestamps in the line protocol batch.
// Use `ms` for milliseconds, `s` for seconds, `us` or `u` for microseconds, or `ns` or `n` for nanoseconds.
// Optional — defaults to nanosecond precision if omitted.
type CompatibilityPrecisionParam = PrecisionWriteCompatibility

// Db defines model for db.
type Db = string

// DbQueryParam defines model for dbQueryParam.
type DbQueryParam = string

// DbWriteParam defines model for dbWriteParam.
type DbWriteParam = string

// FormatRequired The format of data in the response body.
// `json_lines` is the canonical name; `jsonl` is accepted as an alias.
type FormatRequired = Format

// PrecisionParam The precision for unix timestamps in the line protocol batch.
//
// Supported values:
// - `auto` (default): Automatically detects precision based on timestamp magnitude
// - `nanosecond`: Nanoseconds
// - `microsecond`: Microseconds
// - `millisecond`: Milliseconds
// - `second`: Seconds
type PrecisionParam = PrecisionWrite

// QuerySqlParam defines model for querySqlParam.
type QuerySqlParam = string

// V1PasswordParam defines model for v1PasswordParam.
type V1PasswordParam = string

// V1UsernameParam defines model for v1UsernameParam.
type V1UsernameParam = string

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorMessage

// QueryRequestBody defines model for queryRequestBody.
type QueryRequestBody = QueryRequestObject

// PostV2WriteTextBody defines parameters for PostV2Write.
type PostV2WriteTextBody = string

// PostV2WriteParams defines parameters for PostV2Write.
type PostV2WriteParams struct {
	// Bucket A database name.
	// InfluxDB creates the database if it doesn't already exist, and then
	// writes all points in the batch to the database.
	//
	// This parameter is named `bucket` for compatibility with InfluxDB v2 client libraries.
	Bucket        string         `form:"bucket" json:"bucket"`
	AcceptPartial *AcceptPartial `form:"accept_partial,omitempty" json:"accept_partial,omitempty"`

	// Precision The precision for unix timestamps in the line protocol batch.
	Precision *CompatibilityPrecisionParam `form:"precision,omitempty" json:"precision,omitempty"`

	// ContentType The content type of the request payload.
	ContentType *LineProtocol `json:"Content-Type,omitempty"`

	// ContentEncoding The compression applied to the line protocol in the request payload.
	// To send a gzip payload, pass `Content-Encoding: gzip` header.
	ContentEncoding *PostV2WriteParamsContentEncoding `json:"Content-Encoding,omitempty"`

	// ContentLength The size of the entity-body, in bytes, sent to InfluxDB.
	ContentLength *int `json:"Content-Length,omitempty"`

	// Accept The content type that the client can understand.
	// Writes only return a response body if they fail (partially or completely)--for example,
	// due to a syntax problem or type mismatch.
	Accept *PostV2WriteParamsAccept `json:"Accept,omitempty"`
}

// PostV2WriteParamsContentEncoding defines parameters for PostV2Write.
type PostV2WriteParamsContentEncoding string

// PostV2WriteParamsAccept defines parameters for PostV2Write.
type PostV2WriteParamsAccept string

// DeleteConfigureDatabaseParams defines parameters for DeleteConfigureDatabase.
type DeleteConfigureDatabaseParams struct {
	// Db The name of the database.
	Db Db `form:"db" json:"db"`

	// DataOnly Delete only data while preserving the database schema and all associated resources
	// (tokens, triggers, last value caches, distinct value caches, processing engine configurations).
	// When `false` (default), the entire database is deleted.
	DataOnly *bool `form:"data_only,omitempty" json:"data_only,omitempty"`

	// RemoveTables Used with `data_only=true` to remove table resources (caches) while preserving
	// database-level resources (tokens, triggers, processing engine configurations).
	// Has no effect when `data_only=false`.
	RemoveTables *bool `form:"remove_tables,omitempty" json:"remove_tables,omitempty"`

	// HardDeleteAt Schedule the database for hard deletion at the specified time.
	// If not provided, the database will be soft deleted.
	// Use ISO 8601 date-time format (for example, "2025-12-31T23:59:59Z").
	//
	// #### Deleting a database cannot be undone
	//
	// Deleting a database is a destructive action.
	// Once a database is deleted, data stored in that database cannot be recovered.
	//
	//
	// Also accepts special string values:
	// - `now` — hard delete immediately
	// - `never` — soft delete only (default behavior)
	// - `default` — use the system default hard deletion time
	HardDeleteAt *time.Time `form:"hard_delete_at,omitempty" json:"hard_delete_at,omitempty"`
}

// GetConfigureDatabaseParams defines parameters for GetConfigureDatabase.
type GetConfigureDatabaseParams struct {
	Format FormatRequired `form:"format" json:"format"`

	// ShowDeleted Include soft-deleted databases in the response.
	// By default, only active databases are returned.
	ShowDeleted *bool `form:"show_deleted,omitempty" json:"show_deleted,omitempty"`
}

// DeleteDatabaseRetentionPeriodParams defines parameters for DeleteDatabaseRetentionPeriod.
type DeleteDatabaseRetentionPeriodParams struct {
	// Db The name of the database.
	Db Db `form:"db" json:"db"`
}

// DeleteConfigureDistinctCacheParams defines parameters for DeleteConfigureDistinctCache.
type DeleteConfigureDistinctCacheParams struct {
	// Db The name of the database.
	Db Db `form:"db" json:"db"`

	// Table The name of the table containing the distinct cache.
	Table string `form:"table" json:"table"`

	// Name The name of the distinct cache to delete.
	Name string `form:"name" json:"name"`
}

// DeleteConfigureLastCacheParams defines parameters for DeleteConfigureLastCache.
type DeleteConfigureLastCacheParams struct {
	// Db The name of the database.
	Db Db `form:"db" json:"db"`

	// Table The name of the table containing the last cache.
	Table string `form:"table" json:"table"`

	// Name The name of the last cache to delete.
	Name string `form:"name" json:"name"`
}

// PostInstallPluginPackagesJSONBody defines parameters for PostInstallPluginPackages.
type PostInstallPluginPackagesJSONBody struct {
	// Packages A list of Python package names to install.
	// Can include version specifiers (e.g., "scipy==1.9.0").
	Packages []string `json:"packages"`
}

// PostInstallPluginPackagesParams defines parameters for PostInstallPluginPackages.
type PostInstallPluginPackagesParams struct {
	// ContentType The format of the data in the request body.
	ContentType *PostInstallPluginPackagesParamsContentType `json:"Content-Type,omitempty"`
}

// PostInstallPluginPackagesParamsContentType defines parameters for PostInstallPluginPackages.
type PostInstallPluginPackagesParamsContentType string

// PostInstallPluginRequirementsJSONBody defines parameters for PostInstallPluginRequirements.
type PostInstallPluginRequirementsJSONBody struct {
	// RequirementsLocation The path to the requirements file containing Python packages to install.
	// Can be a relative path (relative to the plugin directory) or an absolute path.
	RequirementsLocation string `json:"requirements_location"`
}

// PostInstallPluginRequirementsParams defines parameters for PostInstallPluginRequirements.
type PostInstallPluginRequirementsParams struct {
	// ContentType The format of the data in the request body.
	ContentType *PostInstallPluginRequirementsParamsContentType `json:"Content-Type,omitempty"`
}

// PostInstallPluginRequirementsParamsContentType defines parameters for PostInstallPluginRequirements.
type PostInstallPluginRequirementsParamsContentType string

// DeleteConfigureProcessingEngineTriggerParams defines parameters for DeleteConfigureProcessingEngineTrigger.
type DeleteConfigureProcessingEngineTriggerParams struct {
	// Db The name of the database.
	Db          Db     `form:"db" json:"db"`
	TriggerName string `form:"trigger_name" json:"trigger_name"`

	// Force Force deletion of the trigger even if it has active executions.
	// By default, deletion fails if the trigger is currently executing.
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// PostDisableProcessingEngineTriggerParams defines parameters for PostDisableProcessingEngineTrigger.
type PostDisableProcessingEngineTriggerParams struct {
	// Db The database name.
	Db string `form:"db" json:"db"`

	// TriggerName The name of the trigger.
	TriggerName string `form:"trigger_name" json:"trigger_name"`
}

// PostEnableProcessingEngineTriggerParams defines parameters for PostEnableProcessingEngineTrigger.
type PostEnableProcessingEngineTriggerParams struct {
	// Db The database name.
	Db string `form:"db" json:"db"`

	// TriggerName The name of the trigger.
	TriggerName string `form:"trigger_name" json:"trigger_name"`
}

// DeleteConfigureTableParams defines parameters for DeleteConfigureTable.
type DeleteConfigureTableParams struct {
	// Db The name of the database.
	Db    Db     `form:"db" json:"db"`
	Table string `form:"table" json:"table"`

	// DataOnly Delete only data while preserving the table schema and all associated resources
	// (last value caches, distinct value caches).
	// When `false` (default), the entire table is deleted.
	DataOnly *bool `form:"data_only,omitempty" json:"data_only,omitempty"`

	// HardDeleteAt Schedule the table for hard deletion at the specified time.
	// If not provided, the table will be soft deleted.
	// Use ISO 8601 format (for example, "2025-12-31T23:59:59Z").
	//
	//
	// Also accepts special string values:
	// - `now` — hard delete immediately
	// - `never` — soft delete only (default behavior)
	// - `default` — use the system default hard deletion time
	HardDeleteAt *time.Time `form:"hard_delete_at,omitempty" json:"hard_delete_at,omitempty"`
}

// DeleteTokenParams defines parameters for DeleteToken.
type DeleteTokenParams struct {
	// TokenName The name of the token to delete.
	TokenName string `form:"token_name" json:"token_name"`
}

// PostCreateNamedAdminTokenJSONBody defines parameters for PostCreateNamedAdminToken.
type PostCreateNamedAdminTokenJSONBody struct {
	// ExpirySecs Optional expiration time in seconds. If not provided, the token does not expire.
	ExpirySecs *int `json:"expiry_secs,omitempty"`

	// TokenName The name for the admin token.
	TokenName string `json:"token_name"`
}

// PostProcessingEnginePluginRequestJSONBody defines parameters for PostProcessingEnginePluginRequest.
type PostProcessingEnginePluginRequestJSONBody map[string]interface{}

// PostProcessingEnginePluginRequestParams defines parameters for PostProcessingEnginePluginRequest.
type PostProcessingEnginePluginRequestParams struct {
	// ContentType The format of the data in the request body.
	ContentType *PostProcessingEnginePluginRequestParamsContentType `json:"Content-Type,omitempty"`
}

// PostProcessingEnginePluginRequestParamsContentType defines parameters for PostProcessingEnginePluginRequest.
type PostProcessingEnginePluginRequestParamsContentType string

// GetExecuteInfluxQLQueryParams defines parameters for GetExecuteInfluxQLQuery.
type GetExecuteInfluxQLQueryParams struct {
	// Db The name of the database.
	//
	// If you provide a query that specifies the database, you can omit the 'db' parameter from your request.
	Db     *DbQueryParam `form:"db,omitempty" json:"db,omitempty"`
	Q      string        `form:"q" json:"q"`
	Format *string       `form:"format,omitempty" json:"format,omitempty"`

	// Params JSON-encoded query parameters for parameterized queries.
	Params *string `form:"params,omitempty" json:"params,omitempty"`

	// Accept The content type that the client can understand.
	Accept *GetExecuteInfluxQLQueryParamsAccept `json:"Accept,omitempty"`
}

// GetExecuteInfluxQLQueryParamsAccept defines parameters for GetExecuteInfluxQLQuery.
type GetExecuteInfluxQLQueryParamsAccept string

// PostExecuteQueryInfluxQLParams defines parameters for PostExecuteQueryInfluxQL.
type PostExecuteQueryInfluxQLParams struct {
	// Accept The content type that the client can understand.
	Accept *PostExecuteQueryInfluxQLParamsAccept `json:"Accept,omitempty"`

	// ContentType The format of the data in the request body.
	ContentType *PostExecuteQueryInfluxQLParamsContentType `json:"Content-Type,omitempty"`
}

// PostExecuteQueryInfluxQLParamsAccept defines parameters for PostExecuteQueryInfluxQL.
type PostExecuteQueryInfluxQLParamsAccept string

// PostExecuteQueryInfluxQLParamsContentType defines parameters for PostExecuteQueryInfluxQL.
type PostExecuteQueryInfluxQLParamsContentType string

// GetExecuteQuerySQLParams defines parameters for GetExecuteQuerySQL.
type GetExecuteQuerySQLParams struct {
	// Db The name of the database.
	Db Db `form:"db" json:"db"`

	// Q The query to execute.
	Q      QuerySqlParam `form:"q" json:"q"`
	Format *Format       `form:"format,omitempty" json:"format,omitempty"`

	// Params JSON-encoded query parameters for parameterized queries.
	Params *string `form:"params,omitempty" json:"params,omitempty"`

	// Accept The content type that the client can understand.
	Accept *GetExecuteQuerySQLParamsAccept `json:"Accept,omitempty"`

	// ContentType The format of the data in the request body.
	ContentType *GetExecuteQuerySQLParamsContentType `json:"Content-Type,omitempty"`
}

// GetExecuteQuerySQLParamsAccept defines parameters for GetExecuteQuerySQL.
type GetExecuteQuerySQLParamsAccept string

// GetExecuteQuerySQLParamsContentType defines parameters for GetExecuteQuerySQL.
type GetExecuteQuerySQLParamsContentType string

// PostExecuteQuerySQLParams defines parameters for PostExecuteQuerySQL.
type PostExecuteQuerySQLParams struct {
	// Accept The content type that the client can understand.
	Accept *PostExecuteQuerySQLParamsAccept `json:"Accept,omitempty"`

	// ContentType The format of the data in the request body.
	ContentType *PostExecuteQuerySQLParamsContentType `json:"Content-Type,omitempty"`
}

// PostExecuteQuerySQLParamsAccept defines parameters for PostExecuteQuerySQL.
type PostExecuteQuerySQLParamsAccept string

// PostExecuteQuerySQLParamsContentType defines parameters for PostExecuteQuerySQL.
type PostExecuteQuerySQLParamsContentType string

// PostWriteLPTextBody defines parameters for PostWriteLP.
type PostWriteLPTextBody = string

// PostWriteLPParams defines parameters for PostWriteLP.
type PostWriteLPParams struct {
	// Db The name of the database.
	// InfluxDB creates the database if it doesn't already exist, and then
	// writes all points in the batch to the database.
	Db            DbWriteParam   `form:"db" json:"db"`
	AcceptPartial *AcceptPartial `form:"accept_partial,omitempty" json:"accept_partial,omitempty"`

	// Precision The precision for unix timestamps in the line protocol batch.
	Precision *PrecisionParam `form:"precision,omitempty" json:"precision,omitempty"`
	NoSync    *NoSync         `form:"no_sync,omitempty" json:"no_sync,omitempty"`

	// ContentType The content type of the request payload.
	ContentType *LineProtocol `json:"Content-Type,omitempty"`

	// Accept The content type that the client can understand.
	// Writes only return a response body if they fail (partially or completely)--for example,
	// due to a syntax problem or type mismatch.
	Accept *PostWriteLPParamsAccept `json:"Accept,omitempty"`

	// ContentEncoding The compression applied to the line protocol in the request payload.
	// To send a gzip payload, pass `Content-Encoding: gzip` header.
	ContentEncoding *ContentEncoding `json:"Content-Encoding,omitempty"`

	// ContentLength The size of the entity-body, in bytes, sent to InfluxDB.
	ContentLength *ContentLength `json:"Content-Length,omitempty"`
}

// PostWriteLPParamsAccept defines parameters for PostWriteLP.
type PostWriteLPParamsAccept string

// GetV1ExecuteQueryParams defines parameters for GetV1ExecuteQuery.
type GetV1ExecuteQueryParams struct {
	// Chunked If true, the response is divided into chunks of size `chunk_size`.
	Chunked *bool `form:"chunked,omitempty" json:"chunked,omitempty"`

	// ChunkSize The number of records that will go into a chunk.
	// This parameter is only used if `chunked=true`.
	ChunkSize *int `form:"chunk_size,omitempty" json:"chunk_size,omitempty"`

	// Db The database to query. If not provided, the InfluxQL query string must specify the database.
	Db *string `form:"db,omitempty" json:"db,omitempty"`

	// Pretty If true, the JSON response is formatted in a human-readable format.
	Pretty *bool `form:"pretty,omitempty" json:"pretty,omitempty"`

	// Q The InfluxQL query string.
	Q string `form:"q" json:"q"`

	// Epoch Formats timestamps as [unix (epoch) timestamps](/influxdb3/core/reference/glossary/#unix-timestamp) with the specified precision
	// instead of [RFC3339 timestamps](/influxdb3/core/reference/glossary/#rfc3339-timestamp) with nanosecond precision.
	Epoch *EpochCompatibility `form:"epoch,omitempty" json:"epoch,omitempty"`

	// U Username for v1 compatibility authentication.
	// When using Basic authentication or query string authentication, InfluxDB 3 ignores this parameter but allows any arbitrary string for compatibility with InfluxDB 1.x clients.
	U *V1UsernameParam `form:"u,omitempty" json:"u,omitempty"`

	// P Password for v1 compatibility authentication.
	// For query string authentication, pass a database token with write permissions as this parameter.
	// InfluxDB 3 checks that the `p` value is an authorized token.
	P *V1PasswordParam `form:"p,omitempty" json:"p,omitempty"`

	// Rp Retention policy name. Honored but discouraged. InfluxDB 3 doesn't use retention policies.
	Rp *string `form:"rp,omitempty" json:"rp,omitempty"`

	// Accept The content type that the client can understand.
	//
	// If `text/csv` is specified, the `Content-type` response header is `application/csv` and the response is formatted as CSV.
	//
	// Returns an error if the format is invalid or non-UTF8.
	Accept *GetV1ExecuteQueryParamsAccept `json:"Accept,omitempty"`

	// Authorization Authorization header for token-based authentication.
	// Supported schemes:
	// - `Bearer AUTH_TOKEN` - OAuth bearer token scheme
	// - `Token AUTH_TOKEN` - InfluxDB v2 token scheme
	// - `Basic <base64-encoded USERNAME:AUTH_TOKEN>` - Basic authentication (username is ignored)
	Authorization *string `json:"Authorization,omitempty"`
}

// GetV1ExecuteQueryParamsAccept defines parameters for GetV1ExecuteQuery.
type GetV1ExecuteQueryParamsAccept string

// PostExecuteV1QueryJSONBody defines parameters for PostExecuteV1Query.
type PostExecuteV1QueryJSONBody struct {
	// ChunkSize The number of records that will go into a chunk.
	// This parameter is only used if `chunked=true`.
	ChunkSize *int `json:"chunk_size,omitempty"`

	// Chunked If true, the response is divided into chunks of size `chunk_size`.
	Chunked *bool `json:"chunked,omitempty"`

	// Db The database to query. If not provided, the InfluxQL query string must specify the database.
	Db *string `json:"db,omitempty"`

	// Epoch A unix timestamp precision.
	//
	// - `h` for hours
	// - `m` for minutes
	// - `s` for seconds
	// - `ms` for milliseconds
	// - `u` or `µ` for microseconds
	// - `ns` for nanoseconds
	//
	// Formats timestamps as [unix (epoch) timestamps](/influxdb3/core/reference/glossary/#unix-timestamp) with the specified precision
	// instead of [RFC3339 timestamps](/influxdb3/core/reference/glossary/#rfc3339-timestamp) with nanosecond precision.
	Epoch *PostExecuteV1QueryJSONBodyEpoch `json:"epoch,omitempty"`

	// Pretty If true, the JSON response is formatted in a human-readable format.
	Pretty *bool `json:"pretty,omitempty"`

	// Q The InfluxQL query string.
	Q string `json:"q"`
}

// PostExecuteV1QueryFormdataBody defines parameters for PostExecuteV1Query.
type PostExecuteV1QueryFormdataBody struct {
	// ChunkSize The number of records that will go into a chunk.
	// This parameter is only used if `chunked=true`.
	ChunkSize *int `form:"chunk_size,omitempty" json:"chunk_size,omitempty"`

	// Chunked If true, the response is divided into chunks of size `chunk_size`.
	Chunked *bool `form:"chunked,omitempty" json:"chunked,omitempty"`

	// Db The database to query. If not provided, the InfluxQL query string must specify the database.
	Db *string `form:"db,omitempty" json:"db,omitempty"`

	// Epoch A unix timestamp precision.
	//
	// - `h` for hours
	// - `m` for minutes
	// - `s` for seconds
	// - `ms` for milliseconds
	// - `u` or `µ` for microseconds
	// - `ns` for nanoseconds
	//
	// Formats timestamps as [unix (epoch) timestamps](/influxdb3/core/reference/glossary/#unix-timestamp) with the specified precision
	// instead of [RFC3339 timestamps](/influxdb3/core/reference/glossary/#rfc3339-timestamp) with nanosecond precision.
	Epoch *PostExecuteV1QueryFormdataBodyEpoch `form:"epoch,omitempty" json:"epoch,omitempty"`

	// Pretty If true, the JSON response is formatted in a human-readable format.
	Pretty *bool `form:"pretty,omitempty" json:"pretty,omitempty"`

	// Q The InfluxQL query string.
	Q string `form:"q" json:"q"`
}

// PostExecuteV1QueryParams defines parameters for PostExecuteV1Query.
type PostExecuteV1QueryParams struct {
	// Accept The content type that the client can understand.
	//
	// If `text/csv` is specified, the `Content-type` response header is `application/csv` and the response is formatted as CSV.
	//
	// Returns an error if the format is invalid or non-UTF8.
	Accept *PostExecuteV1QueryParamsAccept `json:"Accept,omitempty"`
}

// PostExecuteV1QueryParamsAccept defines parameters for PostExecuteV1Query.
type PostExecuteV1QueryParamsAccept string

// PostExecuteV1QueryJSONBodyEpoch defines parameters for PostExecuteV1Query.
type PostExecuteV1QueryJSONBodyEpoch string

// PostExecuteV1QueryFormdataBodyEpoch defines parameters for PostExecuteV1Query.
type PostExecuteV1QueryFormdataBodyEpoch string

// PostV1WriteTextBody defines parameters for PostV1Write.
type PostV1WriteTextBody = string

// PostV1WriteParams defines parameters for PostV1Write.
type PostV1WriteParams struct {
	// Db The name of the database.
	// InfluxDB creates the database if it doesn't already exist, and then
	// writes all points in the batch to the database.
	Db DbWriteParam `form:"db" json:"db"`

	// Precision The precision for unix timestamps in the line protocol batch.
	Precision *CompatibilityPrecisionParam `form:"precision,omitempty" json:"precision,omitempty"`

	// U Username for v1 compatibility authentication.
	// When using Basic authentication or query string authentication, InfluxDB 3 ignores this parameter but allows any arbitrary string for compatibility with InfluxDB 1.x clients.
	U *V1UsernameParam `form:"u,omitempty" json:"u,omitempty"`

	// P Password for v1 compatibility authentication.
	// For query string authentication, pass a database token with write permissions as this parameter.
	// InfluxDB 3 checks that the `p` value is an authorized token.
	P *V1PasswordParam `form:"p,omitempty" json:"p,omitempty"`

	// Rp Retention policy name. Honored but discouraged. InfluxDB 3 doesn't use retention policies.
	Rp *string `form:"rp,omitempty" json:"rp,omitempty"`

	// Consistency Write consistency level. Ignored by InfluxDB 3. Provided for compatibility with InfluxDB 1.x clients.
	Consistency *string `form:"consistency,omitempty" json:"consistency,omitempty"`

	// Authorization Authorization header for token-based authentication.
	// Supported schemes:
	// - `Bearer AUTH_TOKEN` - OAuth bearer token scheme
	// - `Token AUTH_TOKEN` - InfluxDB v2 token scheme
	// - `Basic <base64-encoded USERNAME:AUTH_TOKEN>` - Basic authentication (username is ignored)
	Authorization *string `json:"Authorization,omitempty"`

	// ContentType The content type of the request payload.
	ContentType *LineProtocol `json:"Content-Type,omitempty"`

	// Accept The content type that the client can understand.
	// Writes only return a response body if they fail (partially or completely)--for example,
	// due to a syntax problem or type mismatch.
	Accept *PostV1WriteParamsAccept `json:"Accept,omitempty"`

	// ContentEncoding The compression applied to the line protocol in the request payload.
	// To send a gzip payload, pass `Content-Encoding: gzip` header.
	ContentEncoding *ContentEncoding `json:"Content-Encoding,omitempty"`

	// ContentLength The size of the entity-body, in bytes, sent to InfluxDB.
	ContentLength *ContentLength `json:"Content-Length,omitempty"`
}

// PostV1WriteParamsAccept defines parameters for PostV1Write.
type PostV1WriteParamsAccept string

// PostV2WriteTextRequestBody defines body for PostV2Write for text/plain ContentType.
type PostV2WriteTextRequestBody = PostV2WriteTextBody

// PostConfigureDatabaseJSONRequestBody defines body for PostConfigureDatabase for application/json ContentType.
type PostConfigureDatabaseJSONRequestBody = CreateDatabaseRequest

// UpdateDatabaseJSONRequestBody defines body for UpdateDatabase for application/json ContentType.
type UpdateDatabaseJSONRequestBody = UpdateDatabaseRequest

// PostConfigureDistinctCacheJSONRequestBody defines body for PostConfigureDistinctCache for application/json ContentType.
type PostConfigureDistinctCacheJSONRequestBody = DistinctCacheCreateRequest

// PostConfigureLastCacheJSONRequestBody defines body for PostConfigureLastCache for application/json ContentType.
type PostConfigureLastCacheJSONRequestBody = LastCacheCreateRequest

// PostInstallPluginPackagesJSONRequestBody defines body for PostInstallPluginPackages for application/json ContentType.
type PostInstallPluginPackagesJSONRequestBody PostInstallPluginPackagesJSONBody

// PostInstallPluginRequirementsJSONRequestBody defines body for PostInstallPluginRequirements for application/json ContentType.
type PostInstallPluginRequirementsJSONRequestBody PostInstallPluginRequirementsJSONBody

// PostConfigureProcessingEngineTriggerJSONRequestBody defines body for PostConfigureProcessingEngineTrigger for application/json ContentType.
type PostConfigureProcessingEngineTriggerJSONRequestBody = ProcessingEngineTriggerRequest

// PostConfigureTableJSONRequestBody defines body for PostConfigureTable for application/json ContentType.
type PostConfigureTableJSONRequestBody = CreateTableRequest

// PostCreateNamedAdminTokenJSONRequestBody defines body for PostCreateNamedAdminToken for application/json ContentType.
type PostCreateNamedAdminTokenJSONRequestBody PostCreateNamedAdminTokenJSONBody

// PostProcessingEnginePluginRequestJSONRequestBody defines body for PostProcessingEnginePluginRequest for application/json ContentType.
type PostProcessingEnginePluginRequestJSONRequestBody PostProcessingEnginePluginRequestJSONBody

// PostTestSchedulingPluginJSONRequestBody defines body for PostTestSchedulingPlugin for application/json ContentType.
type PostTestSchedulingPluginJSONRequestBody = SchedulePluginTestRequest

// PostTestWALPluginJSONRequestBody defines body for PostTestWALPlugin for application/json ContentType.
type PostTestWALPluginJSONRequestBody = WALPluginTestRequest

// PutPluginDirectoryJSONRequestBody defines body for PutPluginDirectory for application/json ContentType.
type PutPluginDirectoryJSONRequestBody = PluginDirectoryRequest

// CreatePluginFileJSONRequestBody defines body for CreatePluginFile for application/json ContentType.
type CreatePluginFileJSONRequestBody = PluginFileRequest

// PutPluginFileJSONRequestBody defines body for PutPluginFile for application/json ContentType.
type PutPluginFileJSONRequestBody = PluginFileRequest

// PostExecuteQueryInfluxQLJSONRequestBody defines body for PostExecuteQueryInfluxQL for application/json ContentType.
type PostExecuteQueryInfluxQLJSONRequestBody = QueryRequestObject

// PostExecuteQuerySQLJSONRequestBody defines body for PostExecuteQuerySQL for application/json ContentType.
type PostExecuteQuerySQLJSONRequestBody = QueryRequestObject

// PostWriteLPTextRequestBody defines body for PostWriteLP for text/plain ContentType.
type PostWriteLPTextRequestBody = PostWriteLPTextBody

// PostExecuteV1QueryJSONRequestBody defines body for PostExecuteV1Query for application/json ContentType.
type PostExecuteV1QueryJSONRequestBody PostExecuteV1QueryJSONBody

// PostExecuteV1QueryFormdataRequestBody defines body for PostExecuteV1Query for application/x-www-form-urlencoded ContentType.
type PostExecuteV1QueryFormdataRequestBody PostExecuteV1QueryFormdataBody

// PostV1WriteTextRequestBody defines body for PostV1Write for text/plain ContentType.
type PostV1WriteTextRequestBody = PostV1WriteTextBody
