// Package influxdb3enterprise provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package influxdb3enterprise

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BasicAuthenticationScopes       basicAuthenticationContextKey       = "BasicAuthentication.Scopes"
	BearerAuthenticationScopes      bearerAuthenticationContextKey      = "BearerAuthentication.Scopes"
	QuerystringAuthenticationScopes querystringAuthenticationContextKey = "QuerystringAuthentication.Scopes"
	TokenAuthenticationScopes       tokenAuthenticationContextKey       = "TokenAuthentication.Scopes"
)

// Defines values for ApiPermissionResourceType.
const (
	AdminToken ApiPermissionResourceType = "admin_token"
	Database   ApiPermissionResourceType = "database"
	Role       ApiPermissionResourceType = "role"
	Token      ApiPermissionResourceType = "token"
	User       ApiPermissionResourceType = "user"
)

// Valid indicates whether the value is a known member of the ApiPermissionResourceType enum.
func (e ApiPermissionResourceType) Valid() bool {
	switch e {
	case AdminToken:
		return true
	case Database:
		return true
	case Role:
		return true
	case Token:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for BackupKind.
const (
	BackupKindFull        BackupKind = "full"
	BackupKindIncremental BackupKind = "incremental"
)

// Valid indicates whether the value is a known member of the BackupKind enum.
func (e BackupKind) Valid() bool {
	switch e {
	case BackupKindFull:
		return true
	case BackupKindIncremental:
		return true
	default:
		return false
	}
}

// Defines values for BackupStatus.
const (
	BackupStatusCompleted  BackupStatus = "completed"
	BackupStatusFailed     BackupStatus = "failed"
	BackupStatusInProgress BackupStatus = "in_progress"
)

// Valid indicates whether the value is a known member of the BackupStatus enum.
func (e BackupStatus) Valid() bool {
	switch e {
	case BackupStatusCompleted:
		return true
	case BackupStatusFailed:
		return true
	case BackupStatusInProgress:
		return true
	default:
		return false
	}
}

// Defines values for BulkImportColumnType.
const (
	BulkImportColumnTypeBool   BulkImportColumnType = "bool"
	BulkImportColumnTypeF64    BulkImportColumnType = "f64"
	BulkImportColumnTypeI64    BulkImportColumnType = "i64"
	BulkImportColumnTypeString BulkImportColumnType = "string"
	BulkImportColumnTypeTag    BulkImportColumnType = "tag"
	BulkImportColumnTypeTime   BulkImportColumnType = "time"
	BulkImportColumnTypeU64    BulkImportColumnType = "u64"
)

// Valid indicates whether the value is a known member of the BulkImportColumnType enum.
func (e BulkImportColumnType) Valid() bool {
	switch e {
	case BulkImportColumnTypeBool:
		return true
	case BulkImportColumnTypeF64:
		return true
	case BulkImportColumnTypeI64:
		return true
	case BulkImportColumnTypeString:
		return true
	case BulkImportColumnTypeTag:
		return true
	case BulkImportColumnTypeTime:
		return true
	case BulkImportColumnTypeU64:
		return true
	default:
		return false
	}
}

// Defines values for BulkImportJobStatus.
const (
	BulkImportJobStatusCompacted      BulkImportJobStatus = "compacted"
	BulkImportJobStatusDispatched     BulkImportJobStatus = "dispatched"
	BulkImportJobStatusFailed         BulkImportJobStatus = "failed"
	BulkImportJobStatusImported       BulkImportJobStatus = "imported"
	BulkImportJobStatusQueued         BulkImportJobStatus = "queued"
	BulkImportJobStatusTerminalFailed BulkImportJobStatus = "terminal_failed"
)

// Valid indicates whether the value is a known member of the BulkImportJobStatus enum.
func (e BulkImportJobStatus) Valid() bool {
	switch e {
	case BulkImportJobStatusCompacted:
		return true
	case BulkImportJobStatusDispatched:
		return true
	case BulkImportJobStatusFailed:
		return true
	case BulkImportJobStatusImported:
		return true
	case BulkImportJobStatusQueued:
		return true
	case BulkImportJobStatusTerminalFailed:
		return true
	default:
		return false
	}
}

// Defines values for ContentEncoding.
const (
	ContentEncodingGzip     ContentEncoding = "gzip"
	ContentEncodingIdentity ContentEncoding = "identity"
)

// Valid indicates whether the value is a known member of the ContentEncoding enum.
func (e ContentEncoding) Valid() bool {
	switch e {
	case ContentEncodingGzip:
		return true
	case ContentEncodingIdentity:
		return true
	default:
		return false
	}
}

// Defines values for CreateBackupRequestType.
const (
	CreateBackupRequestTypeFull CreateBackupRequestType = "full"
)

// Valid indicates whether the value is a known member of the CreateBackupRequestType enum.
func (e CreateBackupRequestType) Valid() bool {
	switch e {
	case CreateBackupRequestTypeFull:
		return true
	default:
		return false
	}
}

// Defines values for CreateBackupStatus.
const (
	CreateBackupStatusInProgress CreateBackupStatus = "in_progress"
)

// Valid indicates whether the value is a known member of the CreateBackupStatus enum.
func (e CreateBackupStatus) Valid() bool {
	switch e {
	case CreateBackupStatusInProgress:
		return true
	default:
		return false
	}
}

// Defines values for CreateRestoreStatus.
const (
	CreateRestoreStatusInProgress CreateRestoreStatus = "in_progress"
)

// Valid indicates whether the value is a known member of the CreateRestoreStatus enum.
func (e CreateRestoreStatus) Valid() bool {
	switch e {
	case CreateRestoreStatusInProgress:
		return true
	default:
		return false
	}
}

// Defines values for CreateTableRequestFieldsType.
const (
	CreateTableRequestFieldsTypeBool    CreateTableRequestFieldsType = "bool"
	CreateTableRequestFieldsTypeFloat64 CreateTableRequestFieldsType = "float64"
	CreateTableRequestFieldsTypeInt64   CreateTableRequestFieldsType = "int64"
	CreateTableRequestFieldsTypeUint64  CreateTableRequestFieldsType = "uint64"
	CreateTableRequestFieldsTypeUtf8    CreateTableRequestFieldsType = "utf8"
)

// Valid indicates whether the value is a known member of the CreateTableRequestFieldsType enum.
func (e CreateTableRequestFieldsType) Valid() bool {
	switch e {
	case CreateTableRequestFieldsTypeBool:
		return true
	case CreateTableRequestFieldsTypeFloat64:
		return true
	case CreateTableRequestFieldsTypeInt64:
		return true
	case CreateTableRequestFieldsTypeUint64:
		return true
	case CreateTableRequestFieldsTypeUtf8:
		return true
	default:
		return false
	}
}

// Defines values for EpochCompatibility.
const (
	EpochCompatibilityH  EpochCompatibility = "h"
	EpochCompatibilityM  EpochCompatibility = "m"
	EpochCompatibilityMs EpochCompatibility = "ms"
	EpochCompatibilityNs EpochCompatibility = "ns"
	EpochCompatibilityS  EpochCompatibility = "s"
	EpochCompatibilityU  EpochCompatibility = "u"
	EpochCompatibilityΜ  EpochCompatibility = "µ"
)

// Valid indicates whether the value is a known member of the EpochCompatibility enum.
func (e EpochCompatibility) Valid() bool {
	switch e {
	case EpochCompatibilityH:
		return true
	case EpochCompatibilityM:
		return true
	case EpochCompatibilityMs:
		return true
	case EpochCompatibilityNs:
		return true
	case EpochCompatibilityS:
		return true
	case EpochCompatibilityU:
		return true
	case EpochCompatibilityΜ:
		return true
	default:
		return false
	}
}

// Defines values for Format.
const (
	FormatCsv       Format = "csv"
	FormatJson      Format = "json"
	FormatJsonLines Format = "json_lines"
	FormatJsonl     Format = "jsonl"
	FormatParquet   Format = "parquet"
	FormatPretty    Format = "pretty"
)

// Valid indicates whether the value is a known member of the Format enum.
func (e Format) Valid() bool {
	switch e {
	case FormatCsv:
		return true
	case FormatJson:
		return true
	case FormatJsonLines:
		return true
	case FormatJsonl:
		return true
	case FormatParquet:
		return true
	case FormatPretty:
		return true
	default:
		return false
	}
}

// Defines values for LineProtocol.
const (
	Textplain            LineProtocol = "text/plain"
	TextplainCharsetUtf8 LineProtocol = "text/plain; charset=utf-8"
)

// Valid indicates whether the value is a known member of the LineProtocol enum.
func (e LineProtocol) Valid() bool {
	switch e {
	case Textplain:
		return true
	case TextplainCharsetUtf8:
		return true
	default:
		return false
	}
}

// Defines values for PermissionDetailsApiActions.
const (
	PermissionDetailsApiActionsRead  PermissionDetailsApiActions = "read"
	PermissionDetailsApiActionsWrite PermissionDetailsApiActions = "write"
)

// Valid indicates whether the value is a known member of the PermissionDetailsApiActions enum.
func (e PermissionDetailsApiActions) Valid() bool {
	switch e {
	case PermissionDetailsApiActionsRead:
		return true
	case PermissionDetailsApiActionsWrite:
		return true
	default:
		return false
	}
}

// Defines values for PermissionDetailsApiResourceType.
const (
	PermissionDetailsApiResourceTypeDb     PermissionDetailsApiResourceType = "db"
	PermissionDetailsApiResourceTypeSystem PermissionDetailsApiResourceType = "system"
)

// Valid indicates whether the value is a known member of the PermissionDetailsApiResourceType enum.
func (e PermissionDetailsApiResourceType) Valid() bool {
	switch e {
	case PermissionDetailsApiResourceTypeDb:
		return true
	case PermissionDetailsApiResourceTypeSystem:
		return true
	default:
		return false
	}
}

// Defines values for PrecisionWriteCompatibility.
const (
	PrecisionWriteCompatibilityMs PrecisionWriteCompatibility = "ms"
	PrecisionWriteCompatibilityN  PrecisionWriteCompatibility = "n"
	PrecisionWriteCompatibilityNs PrecisionWriteCompatibility = "ns"
	PrecisionWriteCompatibilityS  PrecisionWriteCompatibility = "s"
	PrecisionWriteCompatibilityU  PrecisionWriteCompatibility = "u"
	PrecisionWriteCompatibilityUs PrecisionWriteCompatibility = "us"
)

// Valid indicates whether the value is a known member of the PrecisionWriteCompatibility enum.
func (e PrecisionWriteCompatibility) Valid() bool {
	switch e {
	case PrecisionWriteCompatibilityMs:
		return true
	case PrecisionWriteCompatibilityN:
		return true
	case PrecisionWriteCompatibilityNs:
		return true
	case PrecisionWriteCompatibilityS:
		return true
	case PrecisionWriteCompatibilityU:
		return true
	case PrecisionWriteCompatibilityUs:
		return true
	default:
		return false
	}
}

// Defines values for QueryRequestObjectFormat.
const (
	QueryRequestObjectFormatCsv       QueryRequestObjectFormat = "csv"
	QueryRequestObjectFormatJson      QueryRequestObjectFormat = "json"
	QueryRequestObjectFormatJsonLines QueryRequestObjectFormat = "json_lines"
	QueryRequestObjectFormatJsonl     QueryRequestObjectFormat = "jsonl"
	QueryRequestObjectFormatParquet   QueryRequestObjectFormat = "parquet"
	QueryRequestObjectFormatPretty    QueryRequestObjectFormat = "pretty"
)

// Valid indicates whether the value is a known member of the QueryRequestObjectFormat enum.
func (e QueryRequestObjectFormat) Valid() bool {
	switch e {
	case QueryRequestObjectFormatCsv:
		return true
	case QueryRequestObjectFormatJson:
		return true
	case QueryRequestObjectFormatJsonLines:
		return true
	case QueryRequestObjectFormatJsonl:
		return true
	case QueryRequestObjectFormatParquet:
		return true
	case QueryRequestObjectFormatPretty:
		return true
	default:
		return false
	}
}

// Defines values for ResourceTokenObjectPermissionsActions.
const (
	ResourceTokenObjectPermissionsActionsRead  ResourceTokenObjectPermissionsActions = "read"
	ResourceTokenObjectPermissionsActionsWrite ResourceTokenObjectPermissionsActions = "write"
)

// Valid indicates whether the value is a known member of the ResourceTokenObjectPermissionsActions enum.
func (e ResourceTokenObjectPermissionsActions) Valid() bool {
	switch e {
	case ResourceTokenObjectPermissionsActionsRead:
		return true
	case ResourceTokenObjectPermissionsActionsWrite:
		return true
	default:
		return false
	}
}

// Defines values for ResourceTokenObjectPermissionsResourceType.
const (
	ResourceTokenObjectPermissionsResourceTypeDb     ResourceTokenObjectPermissionsResourceType = "db"
	ResourceTokenObjectPermissionsResourceTypeSystem ResourceTokenObjectPermissionsResourceType = "system"
)

// Valid indicates whether the value is a known member of the ResourceTokenObjectPermissionsResourceType enum.
func (e ResourceTokenObjectPermissionsResourceType) Valid() bool {
	switch e {
	case ResourceTokenObjectPermissionsResourceTypeDb:
		return true
	case ResourceTokenObjectPermissionsResourceTypeSystem:
		return true
	default:
		return false
	}
}

// Defines values for TriggerSettingsErrorBehavior.
const (
	Disable TriggerSettingsErrorBehavior = "Disable"
	Log     TriggerSettingsErrorBehavior = "Log"
	Retry   TriggerSettingsErrorBehavior = "Retry"
)

// Valid indicates whether the value is a known member of the TriggerSettingsErrorBehavior enum.
func (e TriggerSettingsErrorBehavior) Valid() bool {
	switch e {
	case Disable:
		return true
	case Log:
		return true
	case Retry:
		return true
	default:
		return false
	}
}

// Defines values for AcceptQueryHeader.
const (
	AcceptQueryHeaderApplicationjson             AcceptQueryHeader = "application/json"
	AcceptQueryHeaderApplicationjsonl            AcceptQueryHeader = "application/jsonl"
	AcceptQueryHeaderApplicationvndApacheParquet AcceptQueryHeader = "application/vnd.apache.parquet"
	AcceptQueryHeaderTextcsv                     AcceptQueryHeader = "text/csv"
)

// Valid indicates whether the value is a known member of the AcceptQueryHeader enum.
func (e AcceptQueryHeader) Valid() bool {
	switch e {
	case AcceptQueryHeaderApplicationjson:
		return true
	case AcceptQueryHeaderApplicationjsonl:
		return true
	case AcceptQueryHeaderApplicationvndApacheParquet:
		return true
	case AcceptQueryHeaderTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for ContentType.
const (
	ContentTypeApplicationjson ContentType = "application/json"
)

// Valid indicates whether the value is a known member of the ContentType enum.
func (e ContentType) Valid() bool {
	switch e {
	case ContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for PostV2WriteParamsContentEncoding.
const (
	PostV2WriteParamsContentEncodingGzip     PostV2WriteParamsContentEncoding = "gzip"
	PostV2WriteParamsContentEncodingIdentity PostV2WriteParamsContentEncoding = "identity"
)

// Valid indicates whether the value is a known member of the PostV2WriteParamsContentEncoding enum.
func (e PostV2WriteParamsContentEncoding) Valid() bool {
	switch e {
	case PostV2WriteParamsContentEncodingGzip:
		return true
	case PostV2WriteParamsContentEncodingIdentity:
		return true
	default:
		return false
	}
}

// Defines values for PostV2WriteParamsAccept.
const (
	PostV2WriteParamsAcceptApplicationjson PostV2WriteParamsAccept = "application/json"
)

// Valid indicates whether the value is a known member of the PostV2WriteParamsAccept enum.
func (e PostV2WriteParamsAccept) Valid() bool {
	switch e {
	case PostV2WriteParamsAcceptApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for PostInstallPluginPackagesParamsContentType.
const (
	PostInstallPluginPackagesParamsContentTypeApplicationjson PostInstallPluginPackagesParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the PostInstallPluginPackagesParamsContentType enum.
func (e PostInstallPluginPackagesParamsContentType) Valid() bool {
	switch e {
	case PostInstallPluginPackagesParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for PostInstallPluginRequirementsParamsContentType.
const (
	PostInstallPluginRequirementsParamsContentTypeApplicationjson PostInstallPluginRequirementsParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the PostInstallPluginRequirementsParamsContentType enum.
func (e PostInstallPluginRequirementsParamsContentType) Valid() bool {
	switch e {
	case PostInstallPluginRequirementsParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for PostProcessingEnginePluginRequestParamsContentType.
const (
	PostProcessingEnginePluginRequestParamsContentTypeApplicationjson PostProcessingEnginePluginRequestParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the PostProcessingEnginePluginRequestParamsContentType enum.
func (e PostProcessingEnginePluginRequestParamsContentType) Valid() bool {
	switch e {
	case PostProcessingEnginePluginRequestParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for GetExecuteInfluxQLQueryParamsAccept.
const (
	GetExecuteInfluxQLQueryParamsAcceptApplicationjson             GetExecuteInfluxQLQueryParamsAccept = "application/json"
	GetExecuteInfluxQLQueryParamsAcceptApplicationjsonl            GetExecuteInfluxQLQueryParamsAccept = "application/jsonl"
	GetExecuteInfluxQLQueryParamsAcceptApplicationvndApacheParquet GetExecuteInfluxQLQueryParamsAccept = "application/vnd.apache.parquet"
	GetExecuteInfluxQLQueryParamsAcceptTextcsv                     GetExecuteInfluxQLQueryParamsAccept = "text/csv"
)

// Valid indicates whether the value is a known member of the GetExecuteInfluxQLQueryParamsAccept enum.
func (e GetExecuteInfluxQLQueryParamsAccept) Valid() bool {
	switch e {
	case GetExecuteInfluxQLQueryParamsAcceptApplicationjson:
		return true
	case GetExecuteInfluxQLQueryParamsAcceptApplicationjsonl:
		return true
	case GetExecuteInfluxQLQueryParamsAcceptApplicationvndApacheParquet:
		return true
	case GetExecuteInfluxQLQueryParamsAcceptTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteQueryInfluxQLParamsAccept.
const (
	PostExecuteQueryInfluxQLParamsAcceptApplicationjson             PostExecuteQueryInfluxQLParamsAccept = "application/json"
	PostExecuteQueryInfluxQLParamsAcceptApplicationjsonl            PostExecuteQueryInfluxQLParamsAccept = "application/jsonl"
	PostExecuteQueryInfluxQLParamsAcceptApplicationvndApacheParquet PostExecuteQueryInfluxQLParamsAccept = "application/vnd.apache.parquet"
	PostExecuteQueryInfluxQLParamsAcceptTextcsv                     PostExecuteQueryInfluxQLParamsAccept = "text/csv"
)

// Valid indicates whether the value is a known member of the PostExecuteQueryInfluxQLParamsAccept enum.
func (e PostExecuteQueryInfluxQLParamsAccept) Valid() bool {
	switch e {
	case PostExecuteQueryInfluxQLParamsAcceptApplicationjson:
		return true
	case PostExecuteQueryInfluxQLParamsAcceptApplicationjsonl:
		return true
	case PostExecuteQueryInfluxQLParamsAcceptApplicationvndApacheParquet:
		return true
	case PostExecuteQueryInfluxQLParamsAcceptTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteQueryInfluxQLParamsContentType.
const (
	PostExecuteQueryInfluxQLParamsContentTypeApplicationjson PostExecuteQueryInfluxQLParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the PostExecuteQueryInfluxQLParamsContentType enum.
func (e PostExecuteQueryInfluxQLParamsContentType) Valid() bool {
	switch e {
	case PostExecuteQueryInfluxQLParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for GetExecuteQuerySQLParamsAccept.
const (
	GetExecuteQuerySQLParamsAcceptApplicationjson             GetExecuteQuerySQLParamsAccept = "application/json"
	GetExecuteQuerySQLParamsAcceptApplicationjsonl            GetExecuteQuerySQLParamsAccept = "application/jsonl"
	GetExecuteQuerySQLParamsAcceptApplicationvndApacheParquet GetExecuteQuerySQLParamsAccept = "application/vnd.apache.parquet"
	GetExecuteQuerySQLParamsAcceptTextcsv                     GetExecuteQuerySQLParamsAccept = "text/csv"
)

// Valid indicates whether the value is a known member of the GetExecuteQuerySQLParamsAccept enum.
func (e GetExecuteQuerySQLParamsAccept) Valid() bool {
	switch e {
	case GetExecuteQuerySQLParamsAcceptApplicationjson:
		return true
	case GetExecuteQuerySQLParamsAcceptApplicationjsonl:
		return true
	case GetExecuteQuerySQLParamsAcceptApplicationvndApacheParquet:
		return true
	case GetExecuteQuerySQLParamsAcceptTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for GetExecuteQuerySQLParamsContentType.
const (
	GetExecuteQuerySQLParamsContentTypeApplicationjson GetExecuteQuerySQLParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the GetExecuteQuerySQLParamsContentType enum.
func (e GetExecuteQuerySQLParamsContentType) Valid() bool {
	switch e {
	case GetExecuteQuerySQLParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteQuerySQLParamsAccept.
const (
	PostExecuteQuerySQLParamsAcceptApplicationjson             PostExecuteQuerySQLParamsAccept = "application/json"
	PostExecuteQuerySQLParamsAcceptApplicationjsonl            PostExecuteQuerySQLParamsAccept = "application/jsonl"
	PostExecuteQuerySQLParamsAcceptApplicationvndApacheParquet PostExecuteQuerySQLParamsAccept = "application/vnd.apache.parquet"
	PostExecuteQuerySQLParamsAcceptTextcsv                     PostExecuteQuerySQLParamsAccept = "text/csv"
)

// Valid indicates whether the value is a known member of the PostExecuteQuerySQLParamsAccept enum.
func (e PostExecuteQuerySQLParamsAccept) Valid() bool {
	switch e {
	case PostExecuteQuerySQLParamsAcceptApplicationjson:
		return true
	case PostExecuteQuerySQLParamsAcceptApplicationjsonl:
		return true
	case PostExecuteQuerySQLParamsAcceptApplicationvndApacheParquet:
		return true
	case PostExecuteQuerySQLParamsAcceptTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteQuerySQLParamsContentType.
const (
	PostExecuteQuerySQLParamsContentTypeApplicationjson PostExecuteQuerySQLParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the PostExecuteQuerySQLParamsContentType enum.
func (e PostExecuteQuerySQLParamsContentType) Valid() bool {
	switch e {
	case PostExecuteQuerySQLParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for GetV1ExecuteQueryParamsAccept.
const (
	GetV1ExecuteQueryParamsAcceptApplicationcsv  GetV1ExecuteQueryParamsAccept = "application/csv"
	GetV1ExecuteQueryParamsAcceptApplicationjson GetV1ExecuteQueryParamsAccept = "application/json"
	GetV1ExecuteQueryParamsAcceptTextcsv         GetV1ExecuteQueryParamsAccept = "text/csv"
)

// Valid indicates whether the value is a known member of the GetV1ExecuteQueryParamsAccept enum.
func (e GetV1ExecuteQueryParamsAccept) Valid() bool {
	switch e {
	case GetV1ExecuteQueryParamsAcceptApplicationcsv:
		return true
	case GetV1ExecuteQueryParamsAcceptApplicationjson:
		return true
	case GetV1ExecuteQueryParamsAcceptTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteV1QueryParamsAccept.
const (
	PostExecuteV1QueryParamsAcceptApplicationcsv  PostExecuteV1QueryParamsAccept = "application/csv"
	PostExecuteV1QueryParamsAcceptApplicationjson PostExecuteV1QueryParamsAccept = "application/json"
	PostExecuteV1QueryParamsAcceptTextcsv         PostExecuteV1QueryParamsAccept = "text/csv"
)

// Valid indicates whether the value is a known member of the PostExecuteV1QueryParamsAccept enum.
func (e PostExecuteV1QueryParamsAccept) Valid() bool {
	switch e {
	case PostExecuteV1QueryParamsAcceptApplicationcsv:
		return true
	case PostExecuteV1QueryParamsAcceptApplicationjson:
		return true
	case PostExecuteV1QueryParamsAcceptTextcsv:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteV1QueryJSONBodyEpoch.
const (
	PostExecuteV1QueryJSONBodyEpochH  PostExecuteV1QueryJSONBodyEpoch = "h"
	PostExecuteV1QueryJSONBodyEpochM  PostExecuteV1QueryJSONBodyEpoch = "m"
	PostExecuteV1QueryJSONBodyEpochMs PostExecuteV1QueryJSONBodyEpoch = "ms"
	PostExecuteV1QueryJSONBodyEpochNs PostExecuteV1QueryJSONBodyEpoch = "ns"
	PostExecuteV1QueryJSONBodyEpochS  PostExecuteV1QueryJSONBodyEpoch = "s"
	PostExecuteV1QueryJSONBodyEpochU  PostExecuteV1QueryJSONBodyEpoch = "u"
	PostExecuteV1QueryJSONBodyEpochΜ  PostExecuteV1QueryJSONBodyEpoch = "µ"
)

// Valid indicates whether the value is a known member of the PostExecuteV1QueryJSONBodyEpoch enum.
func (e PostExecuteV1QueryJSONBodyEpoch) Valid() bool {
	switch e {
	case PostExecuteV1QueryJSONBodyEpochH:
		return true
	case PostExecuteV1QueryJSONBodyEpochM:
		return true
	case PostExecuteV1QueryJSONBodyEpochMs:
		return true
	case PostExecuteV1QueryJSONBodyEpochNs:
		return true
	case PostExecuteV1QueryJSONBodyEpochS:
		return true
	case PostExecuteV1QueryJSONBodyEpochU:
		return true
	case PostExecuteV1QueryJSONBodyEpochΜ:
		return true
	default:
		return false
	}
}

// Defines values for PostExecuteV1QueryFormdataBodyEpoch.
const (
	PostExecuteV1QueryFormdataBodyEpochH  PostExecuteV1QueryFormdataBodyEpoch = "h"
	PostExecuteV1QueryFormdataBodyEpochM  PostExecuteV1QueryFormdataBodyEpoch = "m"
	PostExecuteV1QueryFormdataBodyEpochMs PostExecuteV1QueryFormdataBodyEpoch = "ms"
	PostExecuteV1QueryFormdataBodyEpochNs PostExecuteV1QueryFormdataBodyEpoch = "ns"
	PostExecuteV1QueryFormdataBodyEpochS  PostExecuteV1QueryFormdataBodyEpoch = "s"
	PostExecuteV1QueryFormdataBodyEpochU  PostExecuteV1QueryFormdataBodyEpoch = "u"
	PostExecuteV1QueryFormdataBodyEpochΜ  PostExecuteV1QueryFormdataBodyEpoch = "µ"
)

// Valid indicates whether the value is a known member of the PostExecuteV1QueryFormdataBodyEpoch enum.
func (e PostExecuteV1QueryFormdataBodyEpoch) Valid() bool {
	switch e {
	case PostExecuteV1QueryFormdataBodyEpochH:
		return true
	case PostExecuteV1QueryFormdataBodyEpochM:
		return true
	case PostExecuteV1QueryFormdataBodyEpochMs:
		return true
	case PostExecuteV1QueryFormdataBodyEpochNs:
		return true
	case PostExecuteV1QueryFormdataBodyEpochS:
		return true
	case PostExecuteV1QueryFormdataBodyEpochU:
		return true
	case PostExecuteV1QueryFormdataBodyEpochΜ:
		return true
	default:
		return false
	}
}

// Defines values for PostV1WriteParamsAccept.
const (
	PostV1WriteParamsAcceptApplicationjson PostV1WriteParamsAccept = "application/json"
)

// Valid indicates whether the value is a known member of the PostV1WriteParamsAccept enum.
func (e PostV1WriteParamsAccept) Valid() bool {
	switch e {
	case PostV1WriteParamsAcceptApplicationjson:
		return true
	default:
		return false
	}
}

// AbortDeleteRequestBody Request body for aborting a row-delete request.
type AbortDeleteRequestBody struct {
	// Reason The reason for aborting the row-delete request.
	Reason string `json:"reason"`
}

// AcceptPartial Accept partial writes.
type AcceptPartial = bool

// AdminTokenObject defines model for AdminTokenObject.
type AdminTokenObject struct {
	CreatedAt *time.Time  `json:"created_at,omitempty"`
	Expiry    interface{} `json:"expiry,omitempty"`
	Hash      *string     `json:"hash,omitempty"`
	Id        *int        `json:"id,omitempty"`
	Name      *string     `json:"name,omitempty"`
	Token     *string     `json:"token,omitempty"`
}

// ApiNodeSpec Optional specification for targeting specific nodes in a multi-node InfluxDB 3 Enterprise cluster.
// Use this to control which node(s) should handle the cache or trigger.
type ApiNodeSpec struct {
	// NodeGroup The name of a node group in the cluster.
	// If specified, the cache or trigger will be created on all nodes in this group.
	NodeGroup *string `json:"node_group,omitempty"`

	// NodeId The ID of a specific node in the cluster.
	// If specified, the cache or trigger will only be created on this node.
	NodeId *string `json:"node_id,omitempty"`
}

// ApiPermission A permission granted to a user or role. `resourceType` discriminates the permission category and `actions` lists the granted actions (snake_case) for that category. Database permissions may additionally carry `identifiers` (specific databases) or `allResources: true`.
type ApiPermission struct {
	// Actions The granted actions (snake_case) for this resource type.
	Actions []string `json:"actions"`

	// AllResources Database permissions only. `true` when the permission applies to all databases.
	AllResources *bool `json:"allResources,omitempty"`

	// Identifiers Database permissions only. Specific database names the permission targets. Empty when `allResources` is `true`.
	Identifiers *[]string `json:"identifiers,omitempty"`

	// ResourceType The resource category the permission applies to.
	ResourceType ApiPermissionResourceType `json:"resourceType"`
}

// ApiPermissionResourceType The resource category the permission applies to.
type ApiPermissionResourceType string

// BackupKind The backup type.
type BackupKind string

// BackupStatus The status of a backup or restore.
type BackupStatus string

// BulkImportColumnType The InfluxDB column type for a mapped column. These are the supported `--column` types.
type BulkImportColumnType string

// BulkImportJobStatus The status of a bulk import job.
type BulkImportJobStatus string

// BulkImportUploadRequest Multipart form data for a bulk import upload. Send `database`, `table`, and `file_bytes`, and optionally `column_metadata`.
type BulkImportUploadRequest struct {
	// ColumnMetadata Column metadata for a bulk import. Maps column names to InfluxDB column types to declare tag, field, and time columns.
	ColumnMetadata *ColumnMetadata `json:"column_metadata,omitempty"`

	// Database The target database name.
	Database string `json:"database"`

	// FileBytes The Parquet file bytes. Must be valid Parquet with at least one row.
	FileBytes openapi_types.File `json:"file_bytes"`

	// Table The target table name. The table must already exist.
	Table string `json:"table"`
}

// CancelBackupRequest Request body for cancelling a running backup.
type CancelBackupRequest struct {
	// Name The name of the backup job to cancel.
	Name string `json:"name"`
}

// CancelBackupResponse Response returned when a backup is cancelled.
type CancelBackupResponse struct {
	// BackupName The cancelled backup name.
	BackupName string `json:"backup_name"`
}

// ColumnMetadata Column metadata for a bulk import. Maps column names to InfluxDB column types to declare tag, field, and time columns.
type ColumnMetadata struct {
	// ColumnMapping A map of column name to InfluxDB column type. The JSON key accepts the aliases `column_mapping`, `schema`, and `column_metadata`.
	ColumnMapping map[string]BulkImportColumnType `json:"column_mapping"`
}

// ContentEncoding Content coding.
// Use `gzip` for compressed data or `identity` for unmodified, uncompressed data.
//
// #### Multi-member gzip support
//
// InfluxDB 3 supports multi-member gzip payloads (concatenated gzip files per [RFC 1952](https://www.rfc-editor.org/rfc/rfc1952)).
// This allows you to:
// - Concatenate multiple gzip files and send them in a single request
// - Maintain compatibility with InfluxDB v1 and v2 write endpoints
// - Simplify batch operations using standard compression tools
type ContentEncoding string

// ContentLength The length in decimal number of octets.
type ContentLength = int

// CreateBackupRequest Request body for starting a backup.
type CreateBackupRequest struct {
	// Force Overwrite an existing backup of the same name.
	Force *bool `json:"force,omitempty"`

	// Name The backup name. Defaults to a generated name when omitted.
	Name *string `json:"name,omitempty"`

	// Type The backup type. Only `full` backups are supported.
	Type CreateBackupRequestType `json:"type"`
}

// CreateBackupRequestType The backup type. Only `full` backups are supported.
type CreateBackupRequestType string

// CreateBackupResponse Response returned when a backup starts.
type CreateBackupResponse struct {
	// BackupName The resolved backup name.
	BackupName string `json:"backup_name"`

	// Status The status of a newly started backup. Always `in_progress`.
	Status CreateBackupStatus `json:"status"`
}

// CreateBackupStatus The status of a newly started backup. Always `in_progress`.
type CreateBackupStatus string

// CreateDatabaseRequest defines model for CreateDatabaseRequest.
type CreateDatabaseRequest struct {
	// Db The database name. Database names cannot contain underscores (_).
	// Names must start and end with alphanumeric characters and can contain hyphens (-) in the middle.
	Db string `json:"db"`

	// RetentionPeriod The retention period for the database. Specifies how long data should be retained.
	// Use duration format (for example, "1d", "1h", "30m", "7d").
	RetentionPeriod *string `json:"retention_period,omitempty"`
}

// CreateRestoreRequest Request body for starting a restore.
type CreateRestoreRequest struct {
	// BackupName The name of the backup to restore from. Must not be empty.
	BackupName string `json:"backup_name"`
}

// CreateRestoreResponse Response returned when a restore starts.
type CreateRestoreResponse struct {
	// RestoreId The handle used to track or cancel the restore.
	RestoreId string `json:"restore_id"`

	// Status The status of a newly started restore. Always `in_progress`.
	Status CreateRestoreStatus `json:"status"`
}

// CreateRestoreStatus The status of a newly started restore. Always `in_progress`.
type CreateRestoreStatus string

// CreateTableRequest defines model for CreateTableRequest.
type CreateTableRequest struct {
	Db     string `json:"db"`
	Fields []struct {
		Name string                       `json:"name"`
		Type CreateTableRequestFieldsType `json:"type"`
	} `json:"fields"`

	// RetentionPeriod The retention period for the table. Specifies how long data in this table should be retained.
	// Use duration format (for example, "1d", "1h", "30m", "7d").
	RetentionPeriod *string  `json:"retention_period,omitempty"`
	Table           string   `json:"table"`
	Tags            []string `json:"tags"`
}

// CreateTableRequestFieldsType defines model for CreateTableRequest.Fields.Type.
type CreateTableRequestFieldsType string

// CreateTokenWithPermissionsRequest defines model for CreateTokenWithPermissionsRequest.
type CreateTokenWithPermissionsRequest struct {
	// ExpirySecs Optional expiration time in seconds.
	ExpirySecs *int `json:"expiry_secs,omitempty"`

	// Permissions List of permissions to grant to the token.
	Permissions []PermissionDetailsApi `json:"permissions"`

	// TokenName The name for the resource token.
	TokenName string `json:"token_name"`
}

// DeleteBackupResponse Response returned when a backup is deleted.
type DeleteBackupResponse struct {
	// BackupName The deleted backup name.
	BackupName string `json:"backup_name"`

	// Type The backup type.
	Type BackupKind `json:"type"`
}

// DeleteRequestProgressDto Progress tracking for a single row-delete request.
type DeleteRequestProgressDto struct {
	// InRange Per-level progress counts for run sets that overlap the delete criteria.
	InRange PerLevelCountsDto `json:"in_range"`

	// OutOfRange Progress counts for run sets outside the delete criteria that require only watermark updates.
	OutOfRange OutOfRangeCountsDto `json:"out_of_range"`

	// SequenceId The sequence number of the row-delete request.
	SequenceId int64 `json:"sequence_id"`
}

// DeleteRequestResponse A row-delete request.
type DeleteRequestResponse struct {
	// AbortReason The reason the request was aborted. Present only for aborted requests.
	AbortReason *string `json:"abort_reason,omitempty"`

	// AbortedAt The Unix timestamp (seconds) when the request was aborted. Present only for aborted requests.
	AbortedAt *int64 `json:"aborted_at,omitempty"`

	// CompletedAt The Unix timestamp (seconds) when the request completed. Present only for completed requests.
	CompletedAt *int64 `json:"completed_at,omitempty"`

	// CreatedAt The Unix timestamp (seconds) when the request was created.
	CreatedAt int64 `json:"created_at"`

	// DbId The numeric ID of the target database.
	DbId int64 `json:"db_id"`

	// DbName The name of the target database.
	DbName string `json:"db_name"`

	// DbNameStale Whether the database name no longer matches the current catalog state for the stored database ID.
	DbNameStale bool `json:"db_name_stale"`

	// DeletePredicate The predicate that selects rows to delete.
	DeletePredicate string `json:"delete_predicate"`

	// Disposition The current disposition of the request: `pending`, `completed`, or `aborted`.
	Disposition string `json:"disposition"`

	// MaxTime The maximum timestamp (nanoseconds) of the delete range.
	MaxTime *int64 `json:"max_time,omitempty"`

	// MinTime The minimum timestamp (nanoseconds) of the delete range.
	MinTime *int64 `json:"min_time,omitempty"`

	// Progress Progress tracking for a single row-delete request.
	Progress *DeleteRequestProgressDto `json:"progress,omitempty"`

	// Sequence The sequence number of the row-delete request.
	Sequence int64 `json:"sequence"`

	// TableId The numeric ID of the target table.
	TableId int64 `json:"table_id"`

	// TableName The name of the target table.
	TableName string `json:"table_name"`

	// TableNameStale Whether the table name no longer matches the current catalog state for the stored table ID.
	TableNameStale bool `json:"table_name_stale"`
}

// DistinctCacheCreateRequest defines model for DistinctCacheCreateRequest.
type DistinctCacheCreateRequest struct {
	Columns []string `json:"columns"`
	Db      string   `json:"db"`

	// MaxAge Optional maximum age in seconds.
	MaxAge *int `json:"max_age,omitempty"`

	// MaxCardinality Optional maximum cardinality.
	MaxCardinality *int `json:"max_cardinality,omitempty"`

	// Name Optional cache name.
	Name *string `json:"name,omitempty"`

	// NodeSpec Optional specification for targeting specific nodes in a multi-node InfluxDB 3 Enterprise cluster.
	// Use this to control which node(s) should handle the cache or trigger.
	NodeSpec *ApiNodeSpec `json:"node_spec,omitempty"`
	Table    string       `json:"table"`
}

// EpochCompatibility A unix timestamp precision.
// - `h` for hours
// - `m` for minutes
// - `s` for seconds
// - `ms` for milliseconds
// - `u` or `µ` for microseconds
// - `ns` for nanoseconds
type EpochCompatibility string

// ErrorMessage defines model for ErrorMessage.
type ErrorMessage struct {
	Data  *map[string]interface{} `json:"data,omitempty"`
	Error *string                 `json:"error,omitempty"`
}

// FileIndexCreateRequest Request body for creating a file index.
type FileIndexCreateRequest struct {
	// Columns The columns to use for the file index.
	Columns []string `json:"columns"`

	// Db The database name.
	Db string `json:"db"`

	// Table The table name. If omitted, the file index applies to the database.
	Table *string `json:"table,omitempty"`
}

// FileIndexDeleteRequest Request body for deleting a file index.
type FileIndexDeleteRequest struct {
	// Db The database name.
	Db string `json:"db"`

	// Table The table name. If omitted, deletes the database-level file index.
	Table *string `json:"table,omitempty"`
}

// Format The format of data in the response body.
// `json_lines` is the canonical name; `jsonl` is accepted as an alias.
type Format string

// FullBackupListItem A single backup's manifest.
type FullBackupListItem struct {
	// CompletedAt The completion timestamp. Omitted when the backup is not complete.
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// CreatedAt The creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// Name The backup name.
	Name string `json:"name"`

	// Status The status of a backup or restore.
	Status BackupStatus `json:"status"`

	// TotalFiles The number of files in the backup.
	TotalFiles int64 `json:"total_files"`

	// TotalSizeBytes The total backup size in bytes.
	TotalSizeBytes int64 `json:"total_size_bytes"`

	// Type The backup type.
	Type BackupKind `json:"type"`
}

// GetBackupResponse A single backup's manifest.
type GetBackupResponse = FullBackupListItem

// GetRestoreResponse The status of a single restore.
type GetRestoreResponse struct {
	// BackupName The source backup name.
	BackupName string `json:"backup_name"`

	// CompletedAt The completion timestamp. Null when the restore is not complete.
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// CreatedAt When the restore started.
	CreatedAt time.Time `json:"created_at"`

	// RestoreId The restore handle.
	RestoreId string `json:"restore_id"`

	// Status The status of a backup or restore.
	Status BackupStatus `json:"status"`

	// TotalFiles The number of files.
	TotalFiles int64 `json:"total_files"`

	// TotalSizeBytes The total size in bytes.
	TotalSizeBytes int64 `json:"total_size_bytes"`
}

// LastCacheCreateRequest defines model for LastCacheCreateRequest.
type LastCacheCreateRequest struct {
	// Count Optional count.
	Count *int   `json:"count,omitempty"`
	Db    string `json:"db"`

	// KeyColumns Optional list of key columns.
	KeyColumns *[]string `json:"key_columns,omitempty"`

	// Name Optional cache name.
	Name *string `json:"name,omitempty"`

	// NodeSpec Optional specification for targeting specific nodes in a multi-node InfluxDB 3 Enterprise cluster.
	// Use this to control which node(s) should handle the cache or trigger.
	NodeSpec *ApiNodeSpec `json:"node_spec,omitempty"`
	Table    string       `json:"table"`

	// Ttl Optional time-to-live in seconds.
	Ttl *int `json:"ttl,omitempty"`

	// ValueColumns Optional list of value columns.
	ValueColumns *[]string `json:"value_columns,omitempty"`
}

// LevelProgressDto Progress for a single compaction level.
type LevelProgressDto struct {
	// Processed The number of run sets processed at this level.
	Processed int64 `json:"processed"`

	// Total The total number of run sets at this level.
	Total int64 `json:"total"`
}

// LineProtocol `text/plain` is the content type for line protocol. `UTF-8` is the default character set.
type LineProtocol string

// ListBackupsResponse Response containing the list of backups.
type ListBackupsResponse struct {
	// Backups All full backups.
	Backups []FullBackupListItem `json:"backups"`
}

// ListRestoresResponse Response containing the list of restores.
type ListRestoresResponse struct {
	// Restores All restores, newest first.
	Restores []RestoreListItem `json:"restores"`
}

// ListUserRolesResponse The roles assigned to a user.
type ListUserRolesResponse struct {
	// Items The roles assigned to the user.
	Items []UserRoleResponse `json:"items"`
}

// OutOfRangeCountsDto Progress counts for run sets outside the delete criteria that require only watermark updates.
type OutOfRangeCountsDto struct {
	// Processed The number of out-of-range run sets processed.
	Processed int64 `json:"processed"`

	// Total The total number of out-of-range run sets.
	Total int64 `json:"total"`
}

// PerLevelCountsDto Per-level progress counts for run sets that overlap the delete criteria.
type PerLevelCountsDto struct {
	// L1 Progress for a single compaction level.
	L1 LevelProgressDto `json:"l1"`

	// L2 Progress for a single compaction level.
	L2 LevelProgressDto `json:"l2"`

	// L3 Progress for a single compaction level.
	L3 LevelProgressDto `json:"l3"`

	// L4 Progress for a single compaction level.
	L4 LevelProgressDto `json:"l4"`
}

// PermissionDetailsApi defines model for PermissionDetailsApi.
type PermissionDetailsApi struct {
	// Actions List of actions to grant.
	Actions []PermissionDetailsApiActions `json:"actions"`

	// ResourceNames List of resource names. Use "*" for all resources.
	ResourceNames []string `json:"resource_names"`

	// ResourceType The type of resource.
	ResourceType PermissionDetailsApiResourceType `json:"resource_type"`
}

// PermissionDetailsApiActions defines model for PermissionDetailsApi.Actions.
type PermissionDetailsApiActions string

// PermissionDetailsApiResourceType The type of resource.
type PermissionDetailsApiResourceType string

// PluginDirectoryRequest Request body for updating plugin directory with multiple files.
type PluginDirectoryRequest struct {
	// Files List of plugin files to include in the directory.
	Files []PluginFileEntry `json:"files"`

	// PluginName The name of the plugin directory to update.
	PluginName string `json:"plugin_name"`
}

// PluginFileEntry Represents a single file in a plugin directory.
type PluginFileEntry struct {
	// Content The content of the file.
	Content string `json:"content"`

	// RelativePath The relative path of the file within the plugin directory.
	RelativePath string `json:"relative_path"`
}

// PluginFileRequest Request body for updating a plugin file.
type PluginFileRequest struct {
	// Content The content of the plugin file.
	Content string `json:"content"`

	// PluginName The name of the plugin file to update.
	PluginName string `json:"plugin_name"`
}

// PrecisionWriteCompatibility The precision for unix timestamps in the line protocol batch.
// Use `ms` for milliseconds, `s` for seconds, `us` or `u` for microseconds, or `ns` or `n` for nanoseconds.
// Optional — defaults to nanosecond precision if omitted.
type PrecisionWriteCompatibility string

// ProcessingEngineTriggerRequest defines model for ProcessingEngineTriggerRequest.
type ProcessingEngineTriggerRequest struct {
	Db string `json:"db"`

	// Disabled Whether the trigger is disabled.
	Disabled bool `json:"disabled"`

	// NodeSpec Optional specification for targeting specific nodes in a multi-node InfluxDB 3 Enterprise cluster.
	// Use this to control which node(s) should handle the cache or trigger.
	NodeSpec *ApiNodeSpec `json:"node_spec,omitempty"`

	// PluginFilename The path and filename of the plugin to execute--for example,
	// `schedule.py` or `endpoints/report.py`.
	// The path can be absolute or relative to the `--plugins-dir` directory configured when starting InfluxDB 3.
	//
	// The plugin file must implement the trigger interface associated with the trigger's specification.
	PluginFilename string `json:"plugin_filename"`

	// TriggerArguments Optional arguments passed to the plugin.
	TriggerArguments *map[string]interface{} `json:"trigger_arguments,omitempty"`
	TriggerName      string                  `json:"trigger_name"`

	// TriggerSettings Configuration for trigger error handling and execution behavior.
	TriggerSettings TriggerSettings `json:"trigger_settings"`

	// TriggerSpecification Specifies when and how the processing engine trigger should be invoked.
	//
	// ## Supported trigger specifications:
	//
	// ### Cron-based scheduling
	// Format: `cron:CRON_EXPRESSION`
	//
	// Uses extended (6-field) cron format (second minute hour day_of_month month day_of_week):
	// ```
	// ┌───────────── second (0-59)
	// │ ┌───────────── minute (0-59)
	// │ │ ┌───────────── hour (0-23)
	// │ │ │ ┌───────────── day of month (1-31)
	// │ │ │ │ ┌───────────── month (1-12)
	// │ │ │ │ │ ┌───────────── day of week (0-6, Sunday=0)
	// │ │ │ │ │ │
	// * * * * * *
	// ```
	// Examples:
	// - `cron:0 0 6 * * 1-5` - Every weekday at 6:00 AM
	// - `cron:0 30 14 * * 5` - Every Friday at 2:30 PM
	// - `cron:0 0 0 1 * *` - First day of every month at midnight
	//
	// ### Interval-based scheduling
	// Format: `every:DURATION`
	//
	// Supported durations: `s` (seconds), `m` (minutes), `h` (hours), `d` (days), `w` (weeks), `M` (months), `y` (years):
	// - `every:30s` - Every 30 seconds
	// - `every:5m` - Every 5 minutes
	// - `every:1h` - Every hour
	// - `every:1d` - Every day
	// - `every:1w` - Every week
	// - `every:1M` - Every month
	// - `every:1y` - Every year
	//
	// **Maximum interval**: 1 year
	//
	// ### Table-based triggers
	// - `all_tables` - Triggers on write events to any table in the database
	// - `table:TABLE_NAME` - Triggers on write events to a specific table
	//
	// ### On-demand triggers
	// Format: `request:REQUEST_PATH`
	//
	// Creates an HTTP endpoint `/api/v3/engine/REQUEST_PATH` for manual invocation:
	// - `request:hello-world` - Creates endpoint `/api/v3/engine/hello-world`
	// - `request:data-export` - Creates endpoint `/api/v3/engine/data-export`
	TriggerSpecification interface{} `json:"trigger_specification"`
}

// QueryConcurrencyLimitResponse The current runtime query concurrency limit.
type QueryConcurrencyLimitResponse struct {
	// MaxConcurrentQueries The maximum number of queries that can run concurrently. Omitted when the limit is set to the maximum allowed value.
	MaxConcurrentQueries *int `json:"max_concurrent_queries,omitempty"`
}

// QueryRequestObject defines model for QueryRequestObject.
type QueryRequestObject struct {
	// Db The name of the database to query.
	// Required if the query (`q`) doesn't specify the database.
	Db string `json:"db"`

	// Format The format of the query results.
	Format *QueryRequestObjectFormat `json:"format,omitempty"`

	// Params Additional parameters for the query.
	// Use this field to pass query parameters.
	Params *map[string]interface{} `json:"params,omitempty"`

	// Q The query to execute.
	Q string `json:"q"`
}

// QueryRequestObjectFormat The format of the query results.
type QueryRequestObjectFormat string

// QueryResponse defines model for QueryResponse.
type QueryResponse struct {
	Results *[]map[string]interface{} `json:"results,omitempty"`
}

// ResourceTokenObject defines model for ResourceTokenObject.
type ResourceTokenObject struct {
	// ExpirySecs The expiration time in seconds.
	ExpirySecs  *int `json:"expiry_secs,omitempty"`
	Permissions *[]struct {
		Actions *[]ResourceTokenObjectPermissionsActions `json:"actions,omitempty"`

		// ResourceNames List of resource names. Use "*" for all resources.
		ResourceNames *[]string                                   `json:"resource_names,omitempty"`
		ResourceType  *ResourceTokenObjectPermissionsResourceType `json:"resource_type,omitempty"`
	} `json:"permissions,omitempty"`
	TokenName *string `json:"token_name,omitempty"`
}

// ResourceTokenObjectPermissionsActions defines model for ResourceTokenObject.Permissions.Actions.
type ResourceTokenObjectPermissionsActions string

// ResourceTokenObjectPermissionsResourceType defines model for ResourceTokenObject.Permissions.ResourceType.
type ResourceTokenObjectPermissionsResourceType string

// RestoreListItem A single restore's status.
type RestoreListItem struct {
	// BackupName The source backup name.
	BackupName string `json:"backup_name"`

	// CompletedAt The completion timestamp. Omitted when the restore is not complete.
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// CreatedAt When the restore started.
	CreatedAt time.Time `json:"created_at"`

	// RestoreId The restore handle.
	RestoreId string `json:"restore_id"`

	// Status The status of a backup or restore.
	Status BackupStatus `json:"status"`

	// TotalFiles The number of files.
	TotalFiles int64 `json:"total_files"`

	// TotalSizeBytes The total size in bytes.
	TotalSizeBytes int64 `json:"total_size_bytes"`
}

// RoleByNameResponse A role retrieved by name.
type RoleByNameResponse struct {
	// CreatedAt The Unix timestamp (seconds) when the role was created.
	CreatedAt int64 `json:"createdAt"`

	// Description The role description.
	Description *string `json:"description,omitempty"`

	// Id The numeric ID of the role.
	Id int64 `json:"id"`

	// IsRequiredRole Whether the role is a required role.
	IsRequiredRole bool `json:"isRequiredRole"`

	// Name The role name.
	Name string `json:"name"`

	// UpdatedAt The Unix timestamp (seconds) when the role was last updated.
	UpdatedAt int64 `json:"updatedAt"`
}

// RolePermissionsResponse The permissions granted to a role.
type RolePermissionsResponse struct {
	// Permissions The permissions granted to the role.
	Permissions []ApiPermission `json:"permissions"`
}

// SchedulePluginTestRequest Request body for testing a scheduling plugin.
type SchedulePluginTestRequest struct {
	// CacheName Optional name of the cache to use in the test.
	CacheName *string `json:"cache_name,omitempty"`

	// Database The database name to use for the test.
	Database string `json:"database"`

	// Filename The path and filename of the plugin to test.
	Filename string `json:"filename"`

	// InputArguments Optional key-value pairs of arguments to pass to the plugin.
	InputArguments *map[string]string `json:"input_arguments,omitempty"`

	// Schedule Optional schedule specification in cron or interval format.
	Schedule *string `json:"schedule,omitempty"`
}

// SetQueryConcurrencyLimitRequest Request body for setting the runtime query concurrency limit.
type SetQueryConcurrencyLimitRequest struct {
	// MaxConcurrentQueries The maximum number of queries that can run concurrently. Set to `null` (or omit) to restore the limit configured at server startup. Must be a positive integer; values below 16 require `force=true`.
	MaxConcurrentQueries *int `json:"max_concurrent_queries,omitempty"`
}

// ShowDatabasesResponse defines model for ShowDatabasesResponse.
type ShowDatabasesResponse struct {
	Databases *[]string `json:"databases,omitempty"`
}

// StopNodeRequest Request body for marking a node as stopped in the catalog.
type StopNodeRequest struct {
	// NodeId The ID of the node to mark as stopped.
	NodeId string `json:"node_id"`
}

// TriggerSettings Configuration settings for processing engine trigger error handling and execution behavior.
type TriggerSettings struct {
	// ErrorBehavior Specifies how to handle errors that occur during trigger execution:
	// - `Log`: Log the error and continue (default)
	// - `Retry`: Retry the trigger execution
	// - `Disable`: Disable the trigger after an error
	ErrorBehavior TriggerSettingsErrorBehavior `json:"error_behavior"`

	// RunAsync Whether to run the trigger asynchronously.
	// When `true`, the trigger executes in the background without blocking.
	// When `false`, the trigger executes synchronously.
	RunAsync bool `json:"run_async"`
}

// TriggerSettingsErrorBehavior Specifies how to handle errors that occur during trigger execution:
// - `Log`: Log the error and continue (default)
// - `Retry`: Retry the trigger execution
// - `Disable`: Disable the trigger after an error
type TriggerSettingsErrorBehavior string

// UpdateDatabaseRequest Request schema for updating database configuration.
type UpdateDatabaseRequest struct {
	// RetentionPeriod The retention period for the database. Specifies how long data should be retained.
	// Use duration format (for example, "1d", "1h", "30m", "7d").
	RetentionPeriod *string `json:"retention_period,omitempty"`
}

// UpdateTableRequest Request schema for updating table configuration.
type UpdateTableRequest struct {
	// Db The name of the database containing the table.
	Db string `json:"db"`

	// RetentionPeriod The retention period for the table. Specifies how long data in this table should be retained.
	// Use duration format (for example, "1d", "1h", "30m", "7d").
	RetentionPeriod *string `json:"retention_period,omitempty"`

	// Table The name of the table to update.
	Table string `json:"table"`
}

// UpdateUserRolesRequest Request body for replacing all of a user's role assignments.
type UpdateUserRolesRequest struct {
	// RoleIds The complete set of role IDs to assign to the user.
	RoleIds []int64 `json:"roleIds"`
}

// UpdateUserRolesResponse A user's role assignments after an update.
type UpdateUserRolesResponse struct {
	// Items The roles assigned to the user.
	Items []UserRoleResponse `json:"items"`
}

// UploadedImportInfo The status of a staged or completed bulk import job.
type UploadedImportInfo struct {
	// ColumnMetadata Column metadata for a bulk import. Maps column names to InfluxDB column types to declare tag, field, and time columns.
	ColumnMetadata *ColumnMetadata `json:"column_metadata,omitempty"`

	// CompletedAt When the import completed, in nanoseconds since the Unix epoch.
	CompletedAt *int64 `json:"completed_at,omitempty"`

	// CreatedAt When the uploaded file was ready for import, in nanoseconds since the Unix epoch.
	CreatedAt int64 `json:"created_at"`

	// DbId The ID of the database resolved from the supplied name.
	DbId int `json:"db_id"`

	// Filename The filename of the uploaded Parquet data file.
	Filename string `json:"filename"`

	// IoxParquet Whether the file was written by IOx (richer embedded metadata).
	IoxParquet bool `json:"iox_parquet"`

	// LastMessage The last error message if the job has errored.
	LastMessage *string `json:"last_message,omitempty"`

	// LastUpdatedAt When this info last changed, in nanoseconds since the Unix epoch.
	LastUpdatedAt *int64 `json:"last_updated_at,omitempty"`

	// MaxTimestampNs The maximum timestamp in the file (nanoseconds), from column statistics.
	MaxTimestampNs int64 `json:"max_timestamp_ns"`

	// MinTimestampNs The minimum timestamp in the file (nanoseconds), from column statistics.
	MinTimestampNs int64 `json:"min_timestamp_ns"`

	// RowCount The row count from Parquet metadata.
	RowCount int64 `json:"row_count"`

	// SizeBytes The total size of the uploaded Parquet file in bytes.
	SizeBytes int64 `json:"size_bytes"`

	// StartedAt When the import began, in nanoseconds since the Unix epoch.
	StartedAt *int64 `json:"started_at,omitempty"`

	// Status The status of a bulk import job.
	Status BulkImportJobStatus `json:"status"`

	// TableId The ID of the table resolved from the supplied name.
	TableId int `json:"table_id"`

	// UploadUuid The UUID of the upload.
	UploadUuid string `json:"upload_uuid"`
}

// UserResponse A user account.
type UserResponse struct {
	// CreatedAt The Unix timestamp (seconds) when the user was created.
	CreatedAt int64 `json:"createdAt"`

	// DeletedAt The Unix timestamp (seconds) when the user was deleted. Present only for deleted users.
	DeletedAt *int64 `json:"deletedAt,omitempty"`

	// DisplayName The user's display name.
	DisplayName *string `json:"displayName,omitempty"`

	// OauthId The user's OAuth identity-provider ID. Present when the user has an OAuth login identity.
	OauthId *string `json:"oauthId,omitempty"`

	// OperatorToken The operator token. Returned only when creating the initial user.
	OperatorToken *string `json:"operatorToken,omitempty"`

	// RequiresPasswordReset Whether the user must reset their password on next login. Present when the user has a username and password login identity.
	RequiresPasswordReset *bool `json:"requiresPasswordReset,omitempty"`

	// UpdatedAt The Unix timestamp (seconds) when the user was last updated.
	UpdatedAt int64 `json:"updatedAt"`

	// UserId The numeric ID of the user.
	UserId int64 `json:"userId"`

	// Username The user's username. Present when the user has a username and password login identity.
	Username *string `json:"username,omitempty"`
}

// UserRoleResponse A role assigned to or available to a user.
type UserRoleResponse struct {
	// CreatedAt The Unix timestamp (seconds) when the role was created.
	CreatedAt int64 `json:"createdAt"`

	// Description The role description.
	Description *string `json:"description,omitempty"`

	// Id The numeric ID of the role.
	Id int64 `json:"id"`

	// IsRequiredRole Whether the role is a required role.
	IsRequiredRole bool `json:"isRequiredRole"`

	// Name The role name.
	Name string `json:"name"`

	// UpdatedAt The Unix timestamp (seconds) when the role was last updated.
	UpdatedAt int64 `json:"updatedAt"`
}

// WALPluginTestRequest Request body for testing a write-ahead logging (WAL) plugin.
type WALPluginTestRequest struct {
	// CacheName Optional name of the cache to use in the test.
	CacheName *string `json:"cache_name,omitempty"`

	// Database The database name to use for the test.
	Database string `json:"database"`

	// Filename The path and filename of the plugin to test.
	Filename string `json:"filename"`

	// InputArguments Optional key-value pairs of arguments to pass to the plugin.
	InputArguments *map[string]string `json:"input_arguments,omitempty"`

	// InputLp Line protocol data to use as input for the test.
	InputLp string `json:"input_lp"`
}

// AcceptQueryHeader defines model for AcceptQueryHeader.
type AcceptQueryHeader string

// ContentType defines model for ContentType.
type ContentType string

// CompatibilityPrecisionParam The precision for unix timestamps in the line protocol batch.
// Use `ms` for milliseconds, `s` for seconds, `us` or `u` for microseconds, or `ns` or `n` for nanoseconds.
// Optional — defaults to nanosecond precision if omitted.
type CompatibilityPrecisionParam = PrecisionWriteCompatibility

// Db defines model for db.
type Db = string

// DbQueryParam defines model for dbQueryParam.
type DbQueryParam = string

// DbWriteParam defines model for dbWriteParam.
type DbWriteParam = string

// FormatRequired The format of data in the response body.
// `json_lines` is the canonical name; `jsonl` is accepted as an alias.
type FormatRequired = Format

// QuerySqlParam defines model for querySqlParam.
type QuerySqlParam = string

// V1PasswordParam defines model for v1PasswordParam.
type V1PasswordParam = string

// V1UsernameParam defines model for v1UsernameParam.
type V1UsernameParam = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorMessage

// Forbidden defines model for Forbidden.
type Forbidden = ErrorMessage

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorMessage

// QueryRequestBody defines model for queryRequestBody.
type QueryRequestBody = QueryRequestObject

// basicAuthenticationContextKey is the context key for BasicAuthentication security scheme
type basicAuthenticationContextKey string

// bearerAuthenticationContextKey is the context key for BearerAuthentication security scheme
type bearerAuthenticationContextKey string

// querystringAuthenticationContextKey is the context key for QuerystringAuthentication security scheme
type querystringAuthenticationContextKey string

// tokenAuthenticationContextKey is the context key for TokenAuthentication security scheme
type tokenAuthenticationContextKey string

// PostV2WriteTextBody defines parameters for PostV2Write.
type PostV2WriteTextBody = string

// PostV2WriteParams defines parameters for PostV2Write.
type PostV2WriteParams struct {
	// Bucket A database name.
	// InfluxDB creates the database if it doesn't already exist, and then
	// writes all points in the batch to the database.
	//
	// This parameter is named `bucket` for compatibility with InfluxDB v2 client libraries.
	Bucket        string         `form:"bucket" json:"bucket"`
	AcceptPartial *AcceptPartial `form:"accept_partial,omitempty" json:"accept_partial,omitempty"`

	// Precision The precision for unix timestamps in the line protocol batch.
	Precision *CompatibilityPrecisionParam `form:"precision,omitempty" json:"precision,omitempty"`

	// ContentType The content type of the request payload.
	ContentType *LineProtocol `json:"Content-Type,omitempty"`

	// ContentEncoding The compression applied to the line protocol in the request payload.
	// To send a gzip payload, pass `Content-Encoding: gzip` header.
	ContentEncoding *PostV2WriteParamsContentEncoding `json:"Content-Encoding,omitempty"`

	// ContentLength The size of the entity-body, in bytes, sent to InfluxDB.
	ContentLength *int `json:"Content-Length,omitempty"`

	// Accept The content type that the client can understand.
	// Writes only return a response body if they fail (partially or completely)--for example,
	// due to a syntax problem or type mismatch.
	Accept *PostV2WriteParamsAccept `json:"Accept,omitempty"`
}

// PostV2WriteParamsContentEncoding defines parameters for PostV2Write.
type PostV2WriteParamsContentEncoding string

// PostV2WriteParamsAccept defines parameters for PostV2Write.
type PostV2WriteParamsAccept string

// PostAuthorizeJSONBody defines parameters for PostAuthorize.
type PostAuthorizeJSONBody = map[string]interface{}

// PostAuthorizeRefreshJSONBody defines parameters for PostAuthorizeRefresh.
type PostAuthorizeRefreshJSONBody = map[string]interface{}

// PostAuthorizeResetPasswordJSONBody defines parameters for PostAuthorizeResetPassword.
type PostAuthorizeResetPasswordJSONBody = map[string]interface{}

// DeleteConfigureDatabaseParams defines parameters for DeleteConfigureDatabase.
type DeleteConfigureDatabaseParams struct {
	// Db The name of the database.
	Db Db `form:"db" json:"db"`

	// DataOnly Delete only data while preserving the database schema and all associated resources
	// (tokens, triggers, last value caches, distinct value caches, processing engine configurations).
	// When `false` (default), the entire database is deleted.
	DataOnly *bool `form:"data_only,omitempty" json:"data_only,omitempty"`

	// RemoveTables Used with `data_only=true` to remove table resources (caches) while preserving
	// database-level resources (tokens, triggers, processing engine configurations).
	// Has no effect when `data_only=false`.
	RemoveTables *bool `form:"remove_tables,omitempty" json:"remove_tables,omitempty"`

	// HardDeleteAt Schedule the database for hard deletion at the specified time.
	// If not provided, the database will be soft deleted.
	// Use ISO 8601 date-time format (for example, "2025-12-31T23:59:59Z").
	//
	// #### Deleting a database cannot be undone
	//
	// Deleting a database is a destructive action.
	// Once a database is deleted, data stored in that database cannot be recovered.
	//
	//
	// Also accepts special string values:
	// - `now` — hard delete immediately
	// - `never` — soft delete only (default behavior)
	// - `default` — use the system default hard deletion time
	HardDeleteAt *time.Time `form:"hard_delete_at,omitempty" json:"hard_delete_at,omitempty"`
}

// GetConfigureDatabaseParams defines parameters for GetConfigureDatabase.
type GetConfigureDatabaseParams struct {
	Format FormatRequired `form:"format" json:"format"`

	// ShowDeleted Include soft-deleted databases in the response.
	// By default, only active databases are returned.
	ShowDeleted *bool `form:"show_deleted,omitempty" json:"show_deleted,omitempty"`
}

// DeleteDatabaseRetentionPeriodParams defines parameters for DeleteDatabaseRetentionPeriod.
type DeleteDatabaseRetentionPeriodParams struct {
	// Db The name of the database.
	Db Db `form:"db" json:"db"`
}

// DeleteConfigureDistinctCacheJSONBody defines parameters for DeleteConfigureDistinctCache.
type DeleteConfigureDistinctCacheJSONBody = map[string]interface{}

// DeleteConfigureDistinctCacheParams defines parameters for DeleteConfigureDistinctCache.
type DeleteConfigureDistinctCacheParams struct {
	// Db The name of the database.
	Db Db `form:"db" json:"db"`

	// Table The name of the table containing the distinct cache.
	Table string `form:"table" json:"table"`

	// Name The name of the distinct cache to delete.
	Name string `form:"name" json:"name"`
}

// DeleteConfigureLastCacheJSONBody defines parameters for DeleteConfigureLastCache.
type DeleteConfigureLastCacheJSONBody = map[string]interface{}

// DeleteConfigureLastCacheParams defines parameters for DeleteConfigureLastCache.
type DeleteConfigureLastCacheParams struct {
	// Db The name of the database.
	Db Db `form:"db" json:"db"`

	// Table The name of the table containing the last cache.
	Table string `form:"table" json:"table"`

	// Name The name of the last cache to delete.
	Name string `form:"name" json:"name"`
}

// PostInstallPluginPackagesJSONBody defines parameters for PostInstallPluginPackages.
type PostInstallPluginPackagesJSONBody struct {
	// Packages A list of Python package names to install.
	// Can include version specifiers (for example, "scipy==1.9.0").
	Packages []string `json:"packages"`
}

// PostInstallPluginPackagesParams defines parameters for PostInstallPluginPackages.
type PostInstallPluginPackagesParams struct {
	// ContentType The format of the data in the request body.
	ContentType *PostInstallPluginPackagesParamsContentType `json:"Content-Type,omitempty"`
}

// PostInstallPluginPackagesParamsContentType defines parameters for PostInstallPluginPackages.
type PostInstallPluginPackagesParamsContentType string

// PostInstallPluginRequirementsJSONBody defines parameters for PostInstallPluginRequirements.
type PostInstallPluginRequirementsJSONBody struct {
	// RequirementsLocation The path to the requirements file containing Python packages to install.
	// Can be a relative path (relative to the plugin directory) or an absolute path.
	RequirementsLocation string `json:"requirements_location"`
}

// PostInstallPluginRequirementsParams defines parameters for PostInstallPluginRequirements.
type PostInstallPluginRequirementsParams struct {
	// ContentType The format of the data in the request body.
	ContentType *PostInstallPluginRequirementsParamsContentType `json:"Content-Type,omitempty"`
}

// PostInstallPluginRequirementsParamsContentType defines parameters for PostInstallPluginRequirements.
type PostInstallPluginRequirementsParamsContentType string

// DeleteConfigureProcessingEngineTriggerParams defines parameters for DeleteConfigureProcessingEngineTrigger.
type DeleteConfigureProcessingEngineTriggerParams struct {
	// Db The name of the database.
	Db          Db     `form:"db" json:"db"`
	TriggerName string `form:"trigger_name" json:"trigger_name"`

	// Force Force deletion of the trigger even if it has active executions.
	// By default, deletion fails if the trigger is currently executing.
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// PostDisableProcessingEngineTriggerParams defines parameters for PostDisableProcessingEngineTrigger.
type PostDisableProcessingEngineTriggerParams struct {
	// Db The database name.
	Db string `form:"db" json:"db"`

	// TriggerName The name of the trigger.
	TriggerName string `form:"trigger_name" json:"trigger_name"`
}

// PostEnableProcessingEngineTriggerParams defines parameters for PostEnableProcessingEngineTrigger.
type PostEnableProcessingEngineTriggerParams struct {
	// Db The database name.
	Db string `form:"db" json:"db"`

	// TriggerName The name of the trigger.
	TriggerName string `form:"trigger_name" json:"trigger_name"`
}

// PutConfigureQueryConcurrencyLimitParams defines parameters for PutConfigureQueryConcurrencyLimit.
type PutConfigureQueryConcurrencyLimitParams struct {
	// Force Set to `true` to allow setting `max_concurrent_queries` to a value below the minimum of 16.
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// DeleteConfigureTableParams defines parameters for DeleteConfigureTable.
type DeleteConfigureTableParams struct {
	// Db The name of the database.
	Db    Db     `form:"db" json:"db"`
	Table string `form:"table" json:"table"`

	// DataOnly Delete only data while preserving the table schema and all associated resources
	// (last value caches, distinct value caches).
	// When `false` (default), the entire table is deleted.
	DataOnly *bool `form:"data_only,omitempty" json:"data_only,omitempty"`

	// HardDeleteAt Schedule the table for hard deletion at the specified time.
	// If not provided, the table will be soft deleted.
	// Use ISO 8601 format (for example, "2025-12-31T23:59:59Z").
	//
	//
	// Also accepts special string values:
	// - `now` — hard delete immediately
	// - `never` — soft delete only (default behavior)
	// - `default` — use the system default hard deletion time
	HardDeleteAt *time.Time `form:"hard_delete_at,omitempty" json:"hard_delete_at,omitempty"`
}

// DeleteTokenParams defines parameters for DeleteToken.
type DeleteTokenParams struct {
	// TokenName The name of the token to delete.
	TokenName string `form:"token_name" json:"token_name"`
}

// PostCreateNamedAdminTokenJSONBody defines parameters for PostCreateNamedAdminToken.
type PostCreateNamedAdminTokenJSONBody struct {
	// ExpirySecs Optional expiration time in seconds. If not provided, the token does not expire.
	ExpirySecs *int `json:"expiry_secs,omitempty"`

	// TokenName The name for the admin token.
	TokenName string `json:"token_name"`
}

// PostConfigureUserJSONBody defines parameters for PostConfigureUser.
type PostConfigureUserJSONBody = map[string]interface{}

// PostProcessingEnginePluginRequestJSONBody defines parameters for PostProcessingEnginePluginRequest.
type PostProcessingEnginePluginRequestJSONBody map[string]interface{}

// PostProcessingEnginePluginRequestParams defines parameters for PostProcessingEnginePluginRequest.
type PostProcessingEnginePluginRequestParams struct {
	// ContentType The format of the data in the request body.
	ContentType *PostProcessingEnginePluginRequestParamsContentType `json:"Content-Type,omitempty"`
}

// PostProcessingEnginePluginRequestParamsContentType defines parameters for PostProcessingEnginePluginRequest.
type PostProcessingEnginePluginRequestParamsContentType string

// DeleteEnterpriseConfigureTableRetentionPeriodParams defines parameters for DeleteEnterpriseConfigureTableRetentionPeriod.
type DeleteEnterpriseConfigureTableRetentionPeriodParams struct {
	// Db The database name.
	Db string `form:"db" json:"db"`

	// Table The table name.
	Table string `form:"table" json:"table"`
}

// PostEnterpriseConfigureTableRetentionPeriodParams defines parameters for PostEnterpriseConfigureTableRetentionPeriod.
type PostEnterpriseConfigureTableRetentionPeriodParams struct {
	// Db The database name.
	Db string `form:"db" json:"db"`

	// Table The table name.
	Table string `form:"table" json:"table"`

	// Duration The retention period as a human-readable duration (for example, "30d", "24h", "1y").
	Duration string `form:"duration" json:"duration"`
}

// GetExportTablesParams defines parameters for GetExportTables.
type GetExportTablesParams struct {
	// Db The name of the database.
	Db Db `form:"db" json:"db"`
}

// GetExportWindowDataParams defines parameters for GetExportWindowData.
type GetExportWindowDataParams struct {
	// Db The name of the database.
	Db Db `form:"db" json:"db"`

	// Table The table name.
	Table string `form:"table" json:"table"`

	// Windows Comma-separated list of window dates to export (for example, `2026-01-15,2026-01-16`).
	// If omitted, exports all available windows.
	Windows *string `form:"windows,omitempty" json:"windows,omitempty"`
}

// GetExportWindowsParams defines parameters for GetExportWindows.
type GetExportWindowsParams struct {
	// Db The name of the database.
	Db Db `form:"db" json:"db"`

	// Table The table name.
	Table string `form:"table" json:"table"`
}

// GetExecuteInfluxQLQueryJSONBody defines parameters for GetExecuteInfluxQLQuery.
type GetExecuteInfluxQLQueryJSONBody = map[string]interface{}

// GetExecuteInfluxQLQueryParams defines parameters for GetExecuteInfluxQLQuery.
type GetExecuteInfluxQLQueryParams struct {
	// Db The name of the database.
	//
	// If you provide a query that specifies the database, you can omit the 'db' parameter from your request.
	Db     *DbQueryParam `form:"db,omitempty" json:"db,omitempty"`
	Q      string        `form:"q" json:"q"`
	Format *string       `form:"format,omitempty" json:"format,omitempty"`

	// Params JSON-encoded query parameters for parameterized queries.
	Params *string `form:"params,omitempty" json:"params,omitempty"`

	// Accept The content type that the client can understand.
	Accept *GetExecuteInfluxQLQueryParamsAccept `json:"Accept,omitempty"`
}

// GetExecuteInfluxQLQueryParamsAccept defines parameters for GetExecuteInfluxQLQuery.
type GetExecuteInfluxQLQueryParamsAccept string

// PostExecuteQueryInfluxQLParams defines parameters for PostExecuteQueryInfluxQL.
type PostExecuteQueryInfluxQLParams struct {
	// Accept The content type that the client can understand.
	Accept *PostExecuteQueryInfluxQLParamsAccept `json:"Accept,omitempty"`

	// ContentType The format of the data in the request body.
	ContentType *PostExecuteQueryInfluxQLParamsContentType `json:"Content-Type,omitempty"`
}

// PostExecuteQueryInfluxQLParamsAccept defines parameters for PostExecuteQueryInfluxQL.
type PostExecuteQueryInfluxQLParamsAccept string

// PostExecuteQueryInfluxQLParamsContentType defines parameters for PostExecuteQueryInfluxQL.
type PostExecuteQueryInfluxQLParamsContentType string

// GetExecuteQuerySQLJSONBody defines parameters for GetExecuteQuerySQL.
type GetExecuteQuerySQLJSONBody = map[string]interface{}

// GetExecuteQuerySQLParams defines parameters for GetExecuteQuerySQL.
type GetExecuteQuerySQLParams struct {
	// Db The name of the database.
	Db Db `form:"db" json:"db"`

	// Q The query to execute.
	Q      QuerySqlParam `form:"q" json:"q"`
	Format *Format       `form:"format,omitempty" json:"format,omitempty"`

	// Params JSON-encoded query parameters for parameterized queries.
	Params *string `form:"params,omitempty" json:"params,omitempty"`

	// Accept The content type that the client can understand.
	Accept *GetExecuteQuerySQLParamsAccept `json:"Accept,omitempty"`

	// ContentType The format of the data in the request body.
	ContentType *GetExecuteQuerySQLParamsContentType `json:"Content-Type,omitempty"`
}

// GetExecuteQuerySQLParamsAccept defines parameters for GetExecuteQuerySQL.
type GetExecuteQuerySQLParamsAccept string

// GetExecuteQuerySQLParamsContentType defines parameters for GetExecuteQuerySQL.
type GetExecuteQuerySQLParamsContentType string

// PostExecuteQuerySQLParams defines parameters for PostExecuteQuerySQL.
type PostExecuteQuerySQLParams struct {
	// Accept The content type that the client can understand.
	Accept *PostExecuteQuerySQLParamsAccept `json:"Accept,omitempty"`

	// ContentType The format of the data in the request body.
	ContentType *PostExecuteQuerySQLParamsContentType `json:"Content-Type,omitempty"`
}

// PostExecuteQuerySQLParamsAccept defines parameters for PostExecuteQuerySQL.
type PostExecuteQuerySQLParamsAccept string

// PostExecuteQuerySQLParamsContentType defines parameters for PostExecuteQuerySQL.
type PostExecuteQuerySQLParamsContentType string

// GetRowDeleteRequestsParams defines parameters for GetRowDeleteRequests.
type GetRowDeleteRequestsParams struct {
	Db          *string `form:"db,omitempty" json:"db,omitempty"`
	Table       *string `form:"table,omitempty" json:"table,omitempty"`
	Disposition *string `form:"disposition,omitempty" json:"disposition,omitempty"`
	MinSequence *int    `form:"min_sequence,omitempty" json:"min_sequence,omitempty"`
	MaxSequence *int    `form:"max_sequence,omitempty" json:"max_sequence,omitempty"`

	// IncludeProgress Default: (default)
	IncludeProgress *bool `form:"include_progress,omitempty" json:"include_progress,omitempty"`
}

// PostUsersJSONBody defines parameters for PostUsers.
type PostUsersJSONBody = map[string]interface{}

// PostWriteLPTextBody defines parameters for PostWriteLP.
type PostWriteLPTextBody = string

// PostWriteLPParams defines parameters for PostWriteLP.
type PostWriteLPParams struct {
	Db            string  `form:"db" json:"db"`
	Precision     *string `form:"precision,omitempty" json:"precision,omitempty"`
	AcceptPartial *bool   `form:"accept_partial,omitempty" json:"accept_partial,omitempty"`
	NoSync        *bool   `form:"no_sync,omitempty" json:"no_sync,omitempty"`
}

// GetV1ExecuteQueryParams defines parameters for GetV1ExecuteQuery.
type GetV1ExecuteQueryParams struct {
	// Chunked If true, the response is divided into chunks of size `chunk_size`.
	Chunked *bool `form:"chunked,omitempty" json:"chunked,omitempty"`

	// ChunkSize The number of records that will go into a chunk.
	// This parameter is only used if `chunked=true`.
	ChunkSize *int `form:"chunk_size,omitempty" json:"chunk_size,omitempty"`

	// Db The database to query. If not provided, the InfluxQL query string must specify the database.
	Db *string `form:"db,omitempty" json:"db,omitempty"`

	// Pretty If true, the JSON response is formatted in a human-readable format.
	Pretty *bool `form:"pretty,omitempty" json:"pretty,omitempty"`

	// Q The InfluxQL query string.
	Q string `form:"q" json:"q"`

	// Epoch Formats timestamps as [unix (epoch) timestamps](/influxdb3/enterprise/reference/glossary/#unix-timestamp) with the specified precision
	// instead of [RFC3339 timestamps](/influxdb3/enterprise/reference/glossary/#rfc3339-timestamp) with nanosecond precision.
	Epoch *EpochCompatibility `form:"epoch,omitempty" json:"epoch,omitempty"`

	// U Username for v1 compatibility authentication.
	// When using Basic authentication or query string authentication, InfluxDB 3 ignores this parameter but allows any arbitrary string for compatibility with InfluxDB 1.x clients.
	U *V1UsernameParam `form:"u,omitempty" json:"u,omitempty"`

	// P Password for v1 compatibility authentication.
	// For query string authentication, pass a database token with write permissions as this parameter.
	// InfluxDB 3 checks that the `p` value is an authorized token.
	P *V1PasswordParam `form:"p,omitempty" json:"p,omitempty"`

	// Rp Retention policy name. Honored but discouraged. InfluxDB 3 doesn't use retention policies.
	Rp *string `form:"rp,omitempty" json:"rp,omitempty"`

	// Accept The content type that the client can understand.
	//
	// If `text/csv` is specified, the `Content-type` response header is `application/csv` and the response is formatted as CSV.
	//
	// Returns an error if the format is invalid or non-UTF8.
	Accept *GetV1ExecuteQueryParamsAccept `json:"Accept,omitempty"`

	// Authorization Authorization header for token-based authentication.
	// Supported schemes:
	// - `Bearer AUTH_TOKEN` - OAuth bearer token scheme
	// - `Token AUTH_TOKEN` - InfluxDB v2 token scheme
	// - `Basic <base64-encoded USERNAME:AUTH_TOKEN>` - Basic authentication (username is ignored)
	Authorization *string `json:"Authorization,omitempty"`
}

// GetV1ExecuteQueryParamsAccept defines parameters for GetV1ExecuteQuery.
type GetV1ExecuteQueryParamsAccept string

// PostExecuteV1QueryJSONBody defines parameters for PostExecuteV1Query.
type PostExecuteV1QueryJSONBody struct {
	// ChunkSize The number of records that will go into a chunk.
	// This parameter is only used if `chunked=true`.
	ChunkSize *int `json:"chunk_size,omitempty"`

	// Chunked If true, the response is divided into chunks of size `chunk_size`.
	Chunked *bool `json:"chunked,omitempty"`

	// Db The database to query. If not provided, the InfluxQL query string must specify the database.
	Db *string `json:"db,omitempty"`

	// Epoch A unix timestamp precision.
	//
	// - `h` for hours
	// - `m` for minutes
	// - `s` for seconds
	// - `ms` for milliseconds
	// - `u` or `µ` for microseconds
	// - `ns` for nanoseconds
	//
	// Formats timestamps as [unix (epoch) timestamps](/influxdb3/enterprise/reference/glossary/#unix-timestamp) with the specified precision
	// instead of [RFC3339 timestamps](/influxdb3/enterprise/reference/glossary/#rfc3339-timestamp) with nanosecond precision.
	Epoch *PostExecuteV1QueryJSONBodyEpoch `json:"epoch,omitempty"`

	// Pretty If true, the JSON response is formatted in a human-readable format.
	Pretty *bool `json:"pretty,omitempty"`

	// Q The InfluxQL query string.
	Q string `json:"q"`
}

// PostExecuteV1QueryFormdataBody defines parameters for PostExecuteV1Query.
type PostExecuteV1QueryFormdataBody struct {
	// ChunkSize The number of records that will go into a chunk.
	// This parameter is only used if `chunked=true`.
	ChunkSize *int `form:"chunk_size,omitempty" json:"chunk_size,omitempty"`

	// Chunked If true, the response is divided into chunks of size `chunk_size`.
	Chunked *bool `form:"chunked,omitempty" json:"chunked,omitempty"`

	// Db The database to query. If not provided, the InfluxQL query string must specify the database.
	Db *string `form:"db,omitempty" json:"db,omitempty"`

	// Epoch A unix timestamp precision.
	//
	// - `h` for hours
	// - `m` for minutes
	// - `s` for seconds
	// - `ms` for milliseconds
	// - `u` or `µ` for microseconds
	// - `ns` for nanoseconds
	//
	// Formats timestamps as [unix (epoch) timestamps](/influxdb3/enterprise/reference/glossary/#unix-timestamp) with the specified precision
	// instead of [RFC3339 timestamps](/influxdb3/enterprise/reference/glossary/#rfc3339-timestamp) with nanosecond precision.
	Epoch *PostExecuteV1QueryFormdataBodyEpoch `form:"epoch,omitempty" json:"epoch,omitempty"`

	// Pretty If true, the JSON response is formatted in a human-readable format.
	Pretty *bool `form:"pretty,omitempty" json:"pretty,omitempty"`

	// Q The InfluxQL query string.
	Q string `form:"q" json:"q"`
}

// PostExecuteV1QueryParams defines parameters for PostExecuteV1Query.
type PostExecuteV1QueryParams struct {
	// Accept The content type that the client can understand.
	//
	// If `text/csv` is specified, the `Content-type` response header is `application/csv` and the response is formatted as CSV.
	//
	// Returns an error if the format is invalid or non-UTF8.
	Accept *PostExecuteV1QueryParamsAccept `json:"Accept,omitempty"`
}

// PostExecuteV1QueryParamsAccept defines parameters for PostExecuteV1Query.
type PostExecuteV1QueryParamsAccept string

// PostExecuteV1QueryJSONBodyEpoch defines parameters for PostExecuteV1Query.
type PostExecuteV1QueryJSONBodyEpoch string

// PostExecuteV1QueryFormdataBodyEpoch defines parameters for PostExecuteV1Query.
type PostExecuteV1QueryFormdataBodyEpoch string

// PostV1WriteTextBody defines parameters for PostV1Write.
type PostV1WriteTextBody = string

// PostV1WriteParams defines parameters for PostV1Write.
type PostV1WriteParams struct {
	// Db The name of the database.
	// InfluxDB creates the database if it doesn't already exist, and then
	// writes all points in the batch to the database.
	Db DbWriteParam `form:"db" json:"db"`

	// Precision The precision for unix timestamps in the line protocol batch.
	Precision *CompatibilityPrecisionParam `form:"precision,omitempty" json:"precision,omitempty"`

	// U Username for v1 compatibility authentication.
	// When using Basic authentication or query string authentication, InfluxDB 3 ignores this parameter but allows any arbitrary string for compatibility with InfluxDB 1.x clients.
	U *V1UsernameParam `form:"u,omitempty" json:"u,omitempty"`

	// P Password for v1 compatibility authentication.
	// For query string authentication, pass a database token with write permissions as this parameter.
	// InfluxDB 3 checks that the `p` value is an authorized token.
	P *V1PasswordParam `form:"p,omitempty" json:"p,omitempty"`

	// Rp Retention policy name. Honored but discouraged. InfluxDB 3 doesn't use retention policies.
	Rp *string `form:"rp,omitempty" json:"rp,omitempty"`

	// Consistency Write consistency level. Ignored by InfluxDB 3. Provided for compatibility with InfluxDB 1.x clients.
	Consistency *string `form:"consistency,omitempty" json:"consistency,omitempty"`

	// Authorization Authorization header for token-based authentication.
	// Supported schemes:
	// - `Bearer AUTH_TOKEN` - OAuth bearer token scheme
	// - `Token AUTH_TOKEN` - InfluxDB v2 token scheme
	// - `Basic <base64-encoded USERNAME:AUTH_TOKEN>` - Basic authentication (username is ignored)
	Authorization *string `json:"Authorization,omitempty"`

	// ContentType The content type of the request payload.
	ContentType *LineProtocol `json:"Content-Type,omitempty"`

	// Accept The content type that the client can understand.
	// Writes only return a response body if they fail (partially or completely)--for example,
	// due to a syntax problem or type mismatch.
	Accept *PostV1WriteParamsAccept `json:"Accept,omitempty"`

	// ContentEncoding The compression applied to the line protocol in the request payload.
	// To send a gzip payload, pass `Content-Encoding: gzip` header.
	ContentEncoding *ContentEncoding `json:"Content-Encoding,omitempty"`

	// ContentLength The size of the entity-body, in bytes, sent to InfluxDB.
	ContentLength *ContentLength `json:"Content-Length,omitempty"`
}

// PostV1WriteParamsAccept defines parameters for PostV1Write.
type PostV1WriteParamsAccept string

// PostV2WriteTextRequestBody defines body for PostV2Write for text/plain ContentType.
type PostV2WriteTextRequestBody = PostV2WriteTextBody

// PostAuthorizeJSONRequestBody defines body for PostAuthorize for application/json ContentType.
type PostAuthorizeJSONRequestBody = PostAuthorizeJSONBody

// PostAuthorizeRefreshJSONRequestBody defines body for PostAuthorizeRefresh for application/json ContentType.
type PostAuthorizeRefreshJSONRequestBody = PostAuthorizeRefreshJSONBody

// PostAuthorizeResetPasswordJSONRequestBody defines body for PostAuthorizeResetPassword for application/json ContentType.
type PostAuthorizeResetPasswordJSONRequestBody = PostAuthorizeResetPasswordJSONBody

// PostConfigureDatabaseJSONRequestBody defines body for PostConfigureDatabase for application/json ContentType.
type PostConfigureDatabaseJSONRequestBody = CreateDatabaseRequest

// PutConfigureDatabaseJSONRequestBody defines body for PutConfigureDatabase for application/json ContentType.
type PutConfigureDatabaseJSONRequestBody = UpdateDatabaseRequest

// DeleteConfigureDistinctCacheJSONRequestBody defines body for DeleteConfigureDistinctCache for application/json ContentType.
type DeleteConfigureDistinctCacheJSONRequestBody = DeleteConfigureDistinctCacheJSONBody

// PostConfigureDistinctCacheJSONRequestBody defines body for PostConfigureDistinctCache for application/json ContentType.
type PostConfigureDistinctCacheJSONRequestBody = DistinctCacheCreateRequest

// DeleteConfigureLastCacheJSONRequestBody defines body for DeleteConfigureLastCache for application/json ContentType.
type DeleteConfigureLastCacheJSONRequestBody = DeleteConfigureLastCacheJSONBody

// PostConfigureLastCacheJSONRequestBody defines body for PostConfigureLastCache for application/json ContentType.
type PostConfigureLastCacheJSONRequestBody = LastCacheCreateRequest

// PostInstallPluginPackagesJSONRequestBody defines body for PostInstallPluginPackages for application/json ContentType.
type PostInstallPluginPackagesJSONRequestBody PostInstallPluginPackagesJSONBody

// PostInstallPluginRequirementsJSONRequestBody defines body for PostInstallPluginRequirements for application/json ContentType.
type PostInstallPluginRequirementsJSONRequestBody PostInstallPluginRequirementsJSONBody

// PostConfigureProcessingEngineTriggerJSONRequestBody defines body for PostConfigureProcessingEngineTrigger for application/json ContentType.
type PostConfigureProcessingEngineTriggerJSONRequestBody = ProcessingEngineTriggerRequest

// PutConfigureQueryConcurrencyLimitJSONRequestBody defines body for PutConfigureQueryConcurrencyLimit for application/json ContentType.
type PutConfigureQueryConcurrencyLimitJSONRequestBody = SetQueryConcurrencyLimitRequest

// PostConfigureTableJSONRequestBody defines body for PostConfigureTable for application/json ContentType.
type PostConfigureTableJSONRequestBody = CreateTableRequest

// PatchConfigureTableJSONRequestBody defines body for PatchConfigureTable for application/json ContentType.
type PatchConfigureTableJSONRequestBody = UpdateTableRequest

// PostCreateNamedAdminTokenJSONRequestBody defines body for PostCreateNamedAdminToken for application/json ContentType.
type PostCreateNamedAdminTokenJSONRequestBody PostCreateNamedAdminTokenJSONBody

// PostConfigureUserJSONRequestBody defines body for PostConfigureUser for application/json ContentType.
type PostConfigureUserJSONRequestBody = PostConfigureUserJSONBody

// PostProcessingEnginePluginRequestJSONRequestBody defines body for PostProcessingEnginePluginRequest for application/json ContentType.
type PostProcessingEnginePluginRequestJSONRequestBody PostProcessingEnginePluginRequestJSONBody

// DeleteEnterpriseBackupJSONRequestBody defines body for DeleteEnterpriseBackup for application/json ContentType.
type DeleteEnterpriseBackupJSONRequestBody = CancelBackupRequest

// PostEnterpriseBackupJSONRequestBody defines body for PostEnterpriseBackup for application/json ContentType.
type PostEnterpriseBackupJSONRequestBody = CreateBackupRequest

// DeleteEnterpriseConfigureFileIndexJSONRequestBody defines body for DeleteEnterpriseConfigureFileIndex for application/json ContentType.
type DeleteEnterpriseConfigureFileIndexJSONRequestBody = FileIndexDeleteRequest

// PostEnterpriseConfigureFileIndexJSONRequestBody defines body for PostEnterpriseConfigureFileIndex for application/json ContentType.
type PostEnterpriseConfigureFileIndexJSONRequestBody = FileIndexCreateRequest

// PostEnterpriseConfigureNodeStopJSONRequestBody defines body for PostEnterpriseConfigureNodeStop for application/json ContentType.
type PostEnterpriseConfigureNodeStopJSONRequestBody = StopNodeRequest

// PostCreateResourceTokenJSONRequestBody defines body for PostCreateResourceToken for application/json ContentType.
type PostCreateResourceTokenJSONRequestBody = CreateTokenWithPermissionsRequest

// PostEnterpriseImportMultipartRequestBody defines body for PostEnterpriseImport for multipart/form-data ContentType.
type PostEnterpriseImportMultipartRequestBody = BulkImportUploadRequest

// PostEnterpriseRestoreJSONRequestBody defines body for PostEnterpriseRestore for application/json ContentType.
type PostEnterpriseRestoreJSONRequestBody = CreateRestoreRequest

// PostTestSchedulingPluginJSONRequestBody defines body for PostTestSchedulingPlugin for application/json ContentType.
type PostTestSchedulingPluginJSONRequestBody = SchedulePluginTestRequest

// PostTestWALPluginJSONRequestBody defines body for PostTestWALPlugin for application/json ContentType.
type PostTestWALPluginJSONRequestBody = WALPluginTestRequest

// PutPluginDirectoryJSONRequestBody defines body for PutPluginDirectory for application/json ContentType.
type PutPluginDirectoryJSONRequestBody = PluginDirectoryRequest

// PostPluginsFilesJSONRequestBody defines body for PostPluginsFiles for application/json ContentType.
type PostPluginsFilesJSONRequestBody = PluginFileRequest

// PutPluginFileJSONRequestBody defines body for PutPluginFile for application/json ContentType.
type PutPluginFileJSONRequestBody = PluginFileRequest

// GetExecuteInfluxQLQueryJSONRequestBody defines body for GetExecuteInfluxQLQuery for application/json ContentType.
type GetExecuteInfluxQLQueryJSONRequestBody = GetExecuteInfluxQLQueryJSONBody

// PostExecuteQueryInfluxQLJSONRequestBody defines body for PostExecuteQueryInfluxQL for application/json ContentType.
type PostExecuteQueryInfluxQLJSONRequestBody = QueryRequestObject

// GetExecuteQuerySQLJSONRequestBody defines body for GetExecuteQuerySQL for application/json ContentType.
type GetExecuteQuerySQLJSONRequestBody = GetExecuteQuerySQLJSONBody

// PostExecuteQuerySQLJSONRequestBody defines body for PostExecuteQuerySQL for application/json ContentType.
type PostExecuteQuerySQLJSONRequestBody = QueryRequestObject

// PostRowDeleteRequestsBySeqAbortJSONRequestBody defines body for PostRowDeleteRequestsBySeqAbort for application/json ContentType.
type PostRowDeleteRequestsBySeqAbortJSONRequestBody = AbortDeleteRequestBody

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = PostUsersJSONBody

// PutUsersByIdRolesJSONRequestBody defines body for PutUsersByIdRoles for application/json ContentType.
type PutUsersByIdRolesJSONRequestBody = UpdateUserRolesRequest

// PostWriteLPTextRequestBody defines body for PostWriteLP for text/plain ContentType.
type PostWriteLPTextRequestBody = PostWriteLPTextBody

// PostExecuteV1QueryJSONRequestBody defines body for PostExecuteV1Query for application/json ContentType.
type PostExecuteV1QueryJSONRequestBody PostExecuteV1QueryJSONBody

// PostExecuteV1QueryFormdataRequestBody defines body for PostExecuteV1Query for application/x-www-form-urlencoded ContentType.
type PostExecuteV1QueryFormdataRequestBody PostExecuteV1QueryFormdataBody

// PostV1WriteTextRequestBody defines body for PostV1Write for text/plain ContentType.
type PostV1WriteTextRequestBody = PostV1WriteTextBody
